### ISSUE TITLE
Speech synthesis on your own model

### ISSUE THREAD

**Issue by AVor0n** [wladradchenko/wunjo.wladradchenko.ru#1]
Can I use my own language model?

**Comment by wladradchenko** [comment]
> Can I use my own language model?

Yes. You can use your own tts model. You also can train model using extension https://github.com/wladradchenko/advanced.wunjo.wladradchenko.ru. I have specially created this extension to train tts models on voice

**Comment by AVor0n** [comment]
> > Can I use my own language model?
> 
> Yes. You can use your own tts model. You also can train model using extension https://github.com/wladradchenko/advanced.wunjo.wladradchenko.ru. I have specially created this extension to train tts models on voice

Thank you for the answer

**Comment by AVor0n** [comment]
> > Can I use my own language model?
> 
> Yes. You can use your own tts model. You also can train model using extension https://github.com/wladradchenko/advanced.wunjo.wladradchenko.ru. I have specially created this extension to train tts models on voice

Thank you for the answer

**Comment by wladradchenko** [comment]
Additionally, I wanna add what you can use any language. You just need to use in tts folder your phoneme file of language. And if you will use English, than you need to write only English fonts, if Russian, than you need to use only Cyrillic fonts.
