### ISSUE TITLE
ModuleNotFoundError: No module named 'facexlib'

### ISSUE THREAD

**Issue by theYaro** [wladradchenko/wunjo.wladradchenko.ru#11]
(venv) ➜  wunjo.wladradchenko.ru git:(main) pip3 install -r requirements.txt
Collecting Flask (from -r requirements.txt (line 1))
  Obtaining dependency information for Flask from https://files.pythonhosted.org/packages/fd/56/26f0be8adc2b4257df20c1c4260ddd0aa396cf8e75d90ab2f7ff99bc34f9/flask-2.3.3-py3-none-any.whl.metadata
  Downloading flask-2.3.3-py3-none-any.whl.metadata (3.6 kB)
Collecting Flask-Cors (from -r requirements.txt (line 2))
  Obtaining dependency information for Flask-Cors from https://files.pythonhosted.org/packages/10/69/1e6cfb87117568a9de088c32d6258219e9d1ff7c131abf74249ef2031279/Flask_Cors-4.0.0-py2.py3-none-any.whl.metadata
  Downloading Flask_Cors-4.0.0-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting pyyaml (from -r requirements.txt (line 3))
  Obtaining dependency information for pyyaml from https://files.pythonhosted.org/packages/ec/0d/26fb23e8863e0aeaac0c64e03fd27367ad2ae3f3cccf3798ee98ce160368/PyYAML-6.0.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Downloading PyYAML-6.0.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata (2.1 kB)
Collecting loguru (from -r requirements.txt (line 4))
  Obtaining dependency information for loguru from https://files.pythonhosted.org/packages/03/0a/4f6fed21aa246c6b49b561ca55facacc2a44b87d65b8b92362a8e99ba202/loguru-0.7.2-py3-none-any.whl.metadata
  Downloading loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting numpy==1.23.5 (from -r requirements.txt (line 5))
  Downloading numpy-1.23.5-cp311-cp311-macosx_10_9_x86_64.whl (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 9.3 MB/s eta 0:00:00
Collecting nltk (from -r requirements.txt (line 6))
  Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 7.5 MB/s eta 0:00:00
Collecting Unidecode (from -r requirements.txt (line 7))
  Downloading Unidecode-1.3.6-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.9/235.9 kB 5.1 MB/s eta 0:00:00
Collecting inflect (from -r requirements.txt (line 8))
  Obtaining dependency information for inflect from https://files.pythonhosted.org/packages/fb/c6/d9feb758be584f729424390af24687d3a4363d968164f94079f83cd536b4/inflect-7.0.0-py3-none-any.whl.metadata
  Downloading inflect-7.0.0-py3-none-any.whl.metadata (21 kB)
Collecting librosa==0.9.2 (from -r requirements.txt (line 9))
  Downloading librosa-0.9.2-py3-none-any.whl (214 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.3/214.3 kB 4.4 MB/s eta 0:00:00
Collecting torch==2.0.0 (from -r requirements.txt (line 10))
  Downloading torch-2.0.0-cp311-none-macosx_10_9_x86_64.whl (139.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.5/139.5 MB 3.1 MB/s eta 0:00:00
Collecting torchaudio==2.0.1 (from -r requirements.txt (line 11))
  Downloading torchaudio-2.0.1-cp311-cp311-macosx_10_9_x86_64.whl (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 5.5 MB/s eta 0:00:00
Collecting soundfile==0.10.3.post1 (from -r requirements.txt (line 12))
  Downloading SoundFile-0.10.3.post1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-macosx_10_5_x86_64.macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.whl (613 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.4/613.4 kB 4.4 MB/s eta 0:00:00
Collecting flaskwebgui (from -r requirements.txt (line 13))
  Downloading flaskwebgui-1.0.6-py3-none-any.whl (7.3 kB)
Collecting waitress (from -r requirements.txt (line 14))
  Downloading waitress-2.1.2-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 411.4 kB/s eta 0:00:00
Collecting briefcase (from -r requirements.txt (line 15))
  Obtaining dependency information for briefcase from https://files.pythonhosted.org/packages/a2/22/124a61222c93ec322a208f9dbb3c695d1bf2cfcd2b7910e38dbb5c5b42fa/briefcase-0.3.15-py3-none-any.whl.metadata
  Downloading briefcase-0.3.15-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: opencv-python in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 16)) (4.8.0.76)
Requirement already satisfied: Pillow in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 17)) (10.0.0)
Collecting scikit-image (from -r requirements.txt (line 18))
  Obtaining dependency information for scikit-image from https://files.pythonhosted.org/packages/08/53/f28cfb52248665b42db7e45a36ffc3a304fef46b308e5065fe2046e78daf/scikit_image-0.21.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Downloading scikit_image-0.21.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (14 kB)
Collecting kornia (from -r requirements.txt (line 19))
  Obtaining dependency information for kornia from https://files.pythonhosted.org/packages/55/da/72cb83aa364ebb4d0109965e20c5d33d7063ccab15332c3fd0acfd5609c9/kornia-0.7.0-py2.py3-none-any.whl.metadata
  Downloading kornia-0.7.0-py2.py3-none-any.whl.metadata (12 kB)
Collecting face_alignment==1.3.5 (from -r requirements.txt (line 20))
  Obtaining dependency information for face_alignment==1.3.5 from https://files.pythonhosted.org/packages/a1/d1/572b8580cfb026b508e8edbfdafca0e119dfd9b963cc0987db50fe0e5d11/face_alignment-1.3.5-py2.py3-none-any.whl.metadata
  Downloading face_alignment-1.3.5-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting dlib-bin (from -r requirements.txt (line 21))
  Obtaining dependency information for dlib-bin from https://files.pythonhosted.org/packages/f2/76/54bd4979f764fc6443bd84b5254082e9c7e6095ab1eb461c9c85033f085b/dlib_bin-19.24.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Downloading dlib_bin-19.24.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (1.4 kB)
Collecting yacs (from -r requirements.txt (line 22))
  Downloading yacs-0.1.8-py3-none-any.whl (14 kB)
Collecting torchvision==0.15.1 (from -r requirements.txt (line 23))
  Downloading torchvision-0.15.1-cp311-cp311-macosx_10_9_x86_64.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 7.4 MB/s eta 0:00:00
Collecting pydub (from -r requirements.txt (line 24))
  Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Collecting gfpgan (from -r requirements.txt (line 25))
  Downloading gfpgan-1.3.8-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 1.6 MB/s eta 0:00:00
Collecting cog (from -r requirements.txt (line 26))
  Obtaining dependency information for cog from https://files.pythonhosted.org/packages/a4/16/16069418df6989fe964d92494c821154244377fb9bb82b7897ba085b965d/cog-0.8.6-py3-none-any.whl.metadata
  Downloading cog-0.8.6-py3-none-any.whl.metadata (35 kB)
Collecting imageio==2.19.3 (from -r requirements.txt (line 27))
  Downloading imageio-2.19.3-py3-none-any.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 6.0 MB/s eta 0:00:00
Collecting imageio-ffmpeg==0.4.7 (from -r requirements.txt (line 28))
  Downloading imageio_ffmpeg-0.4.7-py3-none-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (22.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.5/22.5 MB 6.8 MB/s eta 0:00:00
Collecting av (from -r requirements.txt (line 29))
  Downloading av-10.0.0-cp311-cp311-macosx_10_9_x86_64.whl (26.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.0/26.0 MB 6.1 MB/s eta 0:00:00
Collecting torch-optimizer (from -r requirements.txt (line 30))
  Downloading torch_optimizer-0.3.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 1.7 MB/s eta 0:00:00
Collecting realesrgan (from -r requirements.txt (line 31))
  Downloading realesrgan-0.3.0-py3-none-any.whl (26 kB)
Collecting onnxruntime (from -r requirements.txt (line 32))
  Obtaining dependency information for onnxruntime from https://files.pythonhosted.org/packages/e7/fb/5ec6f781adaa740d367801282feb4544c39b717f17092b706f2c496366ba/onnxruntime-1.15.1-cp311-cp311-macosx_10_15_x86_64.whl.metadata
  Downloading onnxruntime-1.15.1-cp311-cp311-macosx_10_15_x86_64.whl.metadata (4.0 kB)
Collecting insightface (from -r requirements.txt (line 33))
  Downloading insightface-0.7.3.tar.gz (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 kB 4.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pypinyin (from -r requirements.txt (line 34))
  Obtaining dependency information for pypinyin from https://files.pythonhosted.org/packages/00/fc/3e82bf38739a7b2c4f699245ce6c84ff254723c678c2cdc5d2ecbddf9afb/pypinyin-0.49.0-py2.py3-none-any.whl.metadata
  Downloading pypinyin-0.49.0-py2.py3-none-any.whl.metadata (12 kB)
Collecting audioread>=2.1.9 (from librosa==0.9.2->-r requirements.txt (line 9))
  Downloading audioread-3.0.0.tar.gz (377 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.0/377.0 kB 6.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scipy>=1.2.0 in ./venv/lib/python3.11/site-packages (from librosa==0.9.2->-r requirements.txt (line 9)) (1.11.2)
Collecting scikit-learn>=0.19.1 (from librosa==0.9.2->-r requirements.txt (line 9))
  Obtaining dependency information for scikit-learn>=0.19.1 from https://files.pythonhosted.org/packages/e8/dd/41bc4dfa519bc1a0617b68496120c472f1a1a5db264132d1530c43f059a8/scikit_learn-1.3.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Downloading scikit_learn-1.3.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (11 kB)
Collecting joblib>=0.14 (from librosa==0.9.2->-r requirements.txt (line 9))
  Obtaining dependency information for joblib>=0.14 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting decorator>=4.0.10 (from librosa==0.9.2->-r requirements.txt (line 9))
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting resampy>=0.2.2 (from librosa==0.9.2->-r requirements.txt (line 9))
  Downloading resampy-0.4.2-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 7.6 MB/s eta 0:00:00
Requirement already satisfied: numba>=0.45.1 in ./venv/lib/python3.11/site-packages (from librosa==0.9.2->-r requirements.txt (line 9)) (0.57.1)
Collecting pooch>=1.0 (from librosa==0.9.2->-r requirements.txt (line 9))
  Downloading pooch-1.7.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.11/site-packages (from librosa==0.9.2->-r requirements.txt (line 9)) (23.1)
Requirement already satisfied: filelock in ./venv/lib/python3.11/site-packages (from torch==2.0.0->-r requirements.txt (line 10)) (3.12.3)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.11/site-packages (from torch==2.0.0->-r requirements.txt (line 10)) (4.7.1)
Requirement already satisfied: sympy in ./venv/lib/python3.11/site-packages (from torch==2.0.0->-r requirements.txt (line 10)) (1.12)
Requirement already satisfied: networkx in ./venv/lib/python3.11/site-packages (from torch==2.0.0->-r requirements.txt (line 10)) (3.1)
Requirement already satisfied: jinja2 in ./venv/lib/python3.11/site-packages (from torch==2.0.0->-r requirements.txt (line 10)) (3.1.2)
Collecting cffi>=1.0 (from soundfile==0.10.3.post1->-r requirements.txt (line 12))
  Downloading cffi-1.15.1-cp311-cp311-macosx_10_9_x86_64.whl (179 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: tqdm in ./venv/lib/python3.11/site-packages (from face_alignment==1.3.5->-r requirements.txt (line 20)) (4.66.1)
Requirement already satisfied: requests in ./venv/lib/python3.11/site-packages (from torchvision==0.15.1->-r requirements.txt (line 23)) (2.31.0)
Collecting Werkzeug>=2.3.7 (from Flask->-r requirements.txt (line 1))
  Obtaining dependency information for Werkzeug>=2.3.7 from https://files.pythonhosted.org/packages/9b/59/a7c32e3d8d0e546a206e0552a2c04444544f15c1da4a01df8938d20c6ffc/werkzeug-2.3.7-py3-none-any.whl.metadata
  Downloading werkzeug-2.3.7-py3-none-any.whl.metadata (4.1 kB)
Collecting itsdangerous>=2.1.2 (from Flask->-r requirements.txt (line 1))
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=8.1.3 (from Flask->-r requirements.txt (line 1))
  Obtaining dependency information for click>=8.1.3 from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting blinker>=1.6.2 (from Flask->-r requirements.txt (line 1))
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting regex>=2021.8.3 (from nltk->-r requirements.txt (line 6))
  Obtaining dependency information for regex>=2021.8.3 from https://files.pythonhosted.org/packages/db/88/7c35fafe46fda07246c143a106f71880c3368ac5ef3beef89cc17b3bf12c/regex-2023.8.8-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Downloading regex-2023.8.8-cp311-cp311-macosx_10_9_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 1.4 MB/s eta 0:00:00
Collecting pydantic>=1.9.1 (from inflect->-r requirements.txt (line 8))
  Obtaining dependency information for pydantic>=1.9.1 from https://files.pythonhosted.org/packages/82/06/fafdc75e48b248eff364b4249af4bcc6952225e8f20e8205820afc66e88e/pydantic-2.3.0-py3-none-any.whl.metadata
  Downloading pydantic-2.3.0-py3-none-any.whl.metadata (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 3.3 MB/s eta 0:00:00
Collecting psutil~=5.9 (from flaskwebgui->-r requirements.txt (line 13))
  Downloading psutil-5.9.5-cp36-abi3-macosx_10_9_x86_64.whl (245 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.3/245.3 kB 4.8 MB/s eta 0:00:00
Requirement already satisfied: pip>=23.1.1 in ./venv/lib/python3.11/site-packages (from briefcase->-r requirements.txt (line 15)) (23.2.1)
Requirement already satisfied: setuptools>=60 in ./venv/lib/python3.11/site-packages (from briefcase->-r requirements.txt (line 15)) (68.1.2)
Collecting wheel>=0.37 (from briefcase->-r requirements.txt (line 15))
  Obtaining dependency information for wheel>=0.37 from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
  Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
Collecting build>=0.10 (from briefcase->-r requirements.txt (line 15))
  Obtaining dependency information for build>=0.10 from https://files.pythonhosted.org/packages/93/dd/b464b728b866aaa62785a609e0dd8c72201d62c5f7c53e7c20f4dceb085f/build-1.0.3-py3-none-any.whl.metadata
  Downloading build-1.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting cookiecutter<3.0,>=2.2 (from briefcase->-r requirements.txt (line 15))
  Obtaining dependency information for cookiecutter<3.0,>=2.2 from https://files.pythonhosted.org/packages/75/db/09d6bb7e41a2e775c1f5a75a795e1e524ae82423648752e2445d98a00a48/cookiecutter-2.3.0-py3-none-any.whl.metadata
  Downloading cookiecutter-2.3.0-py3-none-any.whl.metadata (13 kB)
Collecting GitPython<4.0,>=3.1 (from briefcase->-r requirements.txt (line 15))
  Obtaining dependency information for GitPython<4.0,>=3.1 from https://files.pythonhosted.org/packages/0f/c6/bb9e2276b6fed126aa21e292493b45a3df4cfba7cbfcf2ab8809a6b0e718/GitPython-3.1.35-py3-none-any.whl.metadata
  Downloading GitPython-3.1.35-py3-none-any.whl.metadata (10 kB)
Collecting platformdirs<4.0,>=2.6 (from briefcase->-r requirements.txt (line 15))
  Obtaining dependency information for platformdirs<4.0,>=2.6 from https://files.pythonhosted.org/packages/14/51/fe5a0d6ea589f0d4a1b97824fb518962ad48b27cd346dcdfa2405187997a/platformdirs-3.10.0-py3-none-any.whl.metadata
  Downloading platformdirs-3.10.0-py3-none-any.whl.metadata (11 kB)
Collecting rich<14.0,>=12.6 (from briefcase->-r requirements.txt (line 15))
  Obtaining dependency information for rich<14.0,>=12.6 from https://files.pythonhosted.org/packages/8d/5f/21a93b2ec205f4b79853ff6e838e3c99064d5dbe85ec6b05967506f14af0/rich-13.5.2-py3-none-any.whl.metadata
  Downloading rich-13.5.2-py3-none-any.whl.metadata (18 kB)
Collecting tomli-w<2.0,>=1.0 (from briefcase->-r requirements.txt (line 15))
  Downloading tomli_w-1.0.0-py3-none-any.whl (6.0 kB)
Collecting dmgbuild<2.0,>=1.6 (from briefcase->-r requirements.txt (line 15))
  Downloading dmgbuild-1.6.1-py3-none-any.whl (36 kB)
INFO: pip is looking at multiple versions of scikit-image to determine which version is compatible with other requirements. This could take a while.
Collecting scikit-image (from -r requirements.txt (line 18))
  Downloading scikit_image-0.20.0-cp311-cp311-macosx_10_9_x86_64.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 8.2 MB/s eta 0:00:00
Collecting tifffile>=2019.7.26 (from scikit-image->-r requirements.txt (line 18))
  Obtaining dependency information for tifffile>=2019.7.26 from https://files.pythonhosted.org/packages/12/3e/89513f44a10c625121b7d5bc54390d7ac7f2c92a19755c052888febf9730/tifffile-2023.8.30-py3-none-any.whl.metadata
  Downloading tifffile-2023.8.30-py3-none-any.whl.metadata (30 kB)
Collecting PyWavelets>=1.1.1 (from scikit-image->-r requirements.txt (line 18))
  Downloading PyWavelets-1.4.1-cp311-cp311-macosx_10_13_x86_64.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 9.3 MB/s eta 0:00:00
Collecting lazy_loader>=0.1 (from scikit-image->-r requirements.txt (line 18))
  Obtaining dependency information for lazy_loader>=0.1 from https://files.pythonhosted.org/packages/a1/c3/65b3814e155836acacf720e5be3b5757130346670ac454fee29d3eda1381/lazy_loader-0.3-py3-none-any.whl.metadata
  Downloading lazy_loader-0.3-py3-none-any.whl.metadata (4.3 kB)
Collecting basicsr>=1.4.2 (from gfpgan->-r requirements.txt (line 25))
  Downloading basicsr-1.4.2.tar.gz (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.5/172.5 kB 3.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: facexlib>=0.2.5 in ./venv/lib/python3.11/site-packages (from gfpgan->-r requirements.txt (line 25)) (0.3.0)
Collecting lmdb (from gfpgan->-r requirements.txt (line 25))
  Downloading lmdb-1.4.1-cp311-cp311-macosx_10_9_universal2.whl (169 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.5/169.5 kB 4.1 MB/s eta 0:00:00
Collecting tb-nightly (from gfpgan->-r requirements.txt (line 25))
  Obtaining dependency information for tb-nightly from https://files.pythonhosted.org/packages/ba/14/d93e4813a1bb3bc543c8b668b54ece6be2143fcaa7d950d8f4a7043ad6f0/tb_nightly-2.15.0a20230911-py3-none-any.whl.metadata
  Downloading tb_nightly-2.15.0a20230911-py3-none-any.whl.metadata (1.7 kB)
Collecting yapf (from gfpgan->-r requirements.txt (line 25))
  Obtaining dependency information for yapf from https://files.pythonhosted.org/packages/23/75/c374517c09e31bf22d3b3f156d73e0f38d08e29b2afdd607cef5f1e10aa9/yapf-0.40.1-py3-none-any.whl.metadata
  Downloading yapf-0.40.1-py3-none-any.whl.metadata (35 kB)
Collecting attrs<24,>=20.1 (from cog->-r requirements.txt (line 26))
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.6 MB/s eta 0:00:00
Collecting fastapi<0.99.0,>=0.75.2 (from cog->-r requirements.txt (line 26))
  Obtaining dependency information for fastapi<0.99.0,>=0.75.2 from https://files.pythonhosted.org/packages/50/2c/6b94f191519dcc8190e78aff7bcb12c58329d1ab4c8aa11f2def9c214599/fastapi-0.98.0-py3-none-any.whl.metadata
  Downloading fastapi-0.98.0-py3-none-any.whl.metadata (22 kB)
Collecting pydantic>=1.9.1 (from inflect->-r requirements.txt (line 8))
  Obtaining dependency information for pydantic>=1.9.1 from https://files.pythonhosted.org/packages/15/ef/24f51eee3ccb81d42aeee387d4cf43a5d0e8ddafad967bce7754d44b755d/pydantic-1.10.12-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Downloading pydantic-1.10.12-cp311-cp311-macosx_10_9_x86_64.whl.metadata (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.3/149.3 kB 3.5 MB/s eta 0:00:00
Collecting structlog<24,>=20 (from cog->-r requirements.txt (line 26))
  Downloading structlog-23.1.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 2.1 MB/s eta 0:00:00
Collecting uvicorn[standard]<1,>=0.12 (from cog->-r requirements.txt (line 26))
  Obtaining dependency information for uvicorn[standard]<1,>=0.12 from https://files.pythonhosted.org/packages/79/96/b0882a1c3f7ef3dd86879e041212ae5b62b4bd352320889231cc735a8e8f/uvicorn-0.23.2-py3-none-any.whl.metadata
  Downloading uvicorn-0.23.2-py3-none-any.whl.metadata (6.2 kB)
Collecting pytorch-ranger>=0.1.1 (from torch-optimizer->-r requirements.txt (line 30))
  Downloading pytorch_ranger-0.1.1-py3-none-any.whl (14 kB)
Collecting coloredlogs (from onnxruntime->-r requirements.txt (line 32))
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 1.1 MB/s eta 0:00:00
Collecting flatbuffers (from onnxruntime->-r requirements.txt (line 32))
  Obtaining dependency information for flatbuffers from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
  Downloading flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
INFO: pip is looking at multiple versions of onnxruntime to determine which version is compatible with other requirements. This could take a while.
Collecting onnxruntime (from -r requirements.txt (line 32))
  Obtaining dependency information for onnxruntime from https://files.pythonhosted.org/packages/72/37/2e7f4e49fc6cc2a8a4f9c336f6f8ba815d8d2504e054eceae751de9d3169/onnxruntime-1.15.0-cp311-cp311-macosx_10_15_x86_64.whl.metadata
  Downloading onnxruntime-1.15.0-cp311-cp311-macosx_10_15_x86_64.whl.metadata (3.9 kB)
Collecting realesrgan (from -r requirements.txt (line 31))
  Downloading realesrgan-0.2.9-py3-none-any.whl (26 kB)
  Downloading realesrgan-0.2.8-py3-none-any.whl (25 kB)
  Downloading realesrgan-0.2.7-py3-none-any.whl (26 kB)
INFO: pip is still looking at multiple versions of onnxruntime to determine which version is compatible with other requirements. This could take a while.
  Downloading realesrgan-0.2.6-py3-none-any.whl (26 kB)
  Downloading realesrgan-0.2.5.0-py3-none-any.whl (25 kB)
  Downloading realesrgan-0.2.4.0-py3-none-any.whl (25 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading realesrgan-0.2.3.0-py3-none-any.whl (25 kB)
  Downloading realesrgan-0.2.2.6-py3-none-any.whl (24 kB)
  Downloading realesrgan-0.2.2.5-py3-none-any.whl (22 kB)
  Downloading realesrgan-0.2.2.4-py3-none-any.whl (20 kB)
  Downloading realesrgan-0.2.2.3-py3-none-any.whl (18 kB)
  Downloading realesrgan-0.2.1.tar.gz (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 9.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "<string>", line 48, in get_hash
      ModuleNotFoundError: No module named 'facexlib'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/yaroslav/Documents/GitHub/wunjo.wladradchenko.ru/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/yaroslav/Documents/GitHub/wunjo.wladradchenko.ru/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/yaroslav/Documents/GitHub/wunjo.wladradchenko.ru/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4l/bydy9jds7n98pwptvy5r5vvm0000gn/T/pip-build-env-l__7gzoj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4l/bydy9jds7n98pwptvy5r5vvm0000gn/T/pip-build-env-l__7gzoj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4l/bydy9jds7n98pwptvy5r5vvm0000gn/T/pip-build-env-l__7gzoj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/4l/bydy9jds7n98pwptvy5r5vvm0000gn/T/pip-build-env-l__7gzoj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 89, in <module>
        File "<string>", line 65, in write_version_py
        File "<string>", line 51, in get_hash
      ImportError: Unable to get git version
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by theYaro** [comment]
Tried to install facexlib manually, but even after that installation of app gave this error.

**Comment by theYaro** [comment]
Ok, now there is another problem

Requirement already satisfied: realesrgan in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.3.0)
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu
Installing dev requirements...

Unable to install requirements. This may be because one of your
requirements is invalid, or because pip was unable to connect
to the PyPI server.

Log saved to /Users/yaroslav/Documents/GitHub/wunjo.wladradchenko.ru/portable/logs/briefcase.2023_09_12-01_13_37.dev.log

**Comment by wladradchenko** [comment]
Did you do python -m pip install - r requirements.txt? Anyway, you can comment line onnxruntime-gpu and uncomment onnxruntime.
