### ISSUE TITLE
No matching distribution found for onnxruntime-gpu

### ISSUE THREAD

**Issue by theYaro** [wladradchenko/wunjo.wladradchenko.ru#12]
(myenv) ➜  portable git:(main) briefcase dev

[wunjo] Installing requirements...
Collecting tensorboard==1.15.0
  Using cached tensorboard-1.15.0-py3-none-any.whl (3.8 MB)
Requirement already satisfied: Flask in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: Flask-Cors in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (4.0.0)
Requirement already satisfied: pyyaml in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (6.0.1)
Requirement already satisfied: loguru in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.7.2)
Requirement already satisfied: numpy==1.23.5 in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (1.23.5)
Requirement already satisfied: nltk in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (3.8.1)
Requirement already satisfied: Unidecode in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (1.3.6)
Requirement already satisfied: inflect in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (7.0.0)
Requirement already satisfied: librosa==0.9.2 in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.9.2)
Requirement already satisfied: torch==2.0.0 in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (2.0.0)
Requirement already satisfied: torchaudio==2.0.1 in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (2.0.1)
Requirement already satisfied: torchvision==0.15.1 in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.15.1)
Requirement already satisfied: soundfile==0.10.3.post1 in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.10.3.post1)
Requirement already satisfied: flaskwebgui in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (1.0.6)
Requirement already satisfied: waitress in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (2.1.2)
Requirement already satisfied: opencv-python in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (4.8.0.76)
Requirement already satisfied: Pillow in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (10.0.0)
Requirement already satisfied: scikit-image in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.20.0)
Collecting scikit-image
  Obtaining dependency information for scikit-image from https://files.pythonhosted.org/packages/cb/a1/6bc36ba38fe9312271cce46cf2025fcc63be096131747a8f41522a57aaef/scikit_image-0.21.0-cp310-cp310-macosx_10_9_x86_64.whl.metadata
  Using cached scikit_image-0.21.0-cp310-cp310-macosx_10_9_x86_64.whl.metadata (14 kB)
Requirement already satisfied: kornia in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.7.0)
Requirement already satisfied: face_alignment==1.3.5 in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (1.3.5)
Requirement already satisfied: dlib-bin in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (19.24.2)
Requirement already satisfied: yacs in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.1.8)
Requirement already satisfied: pydub in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.25.1)
Requirement already satisfied: gfpgan in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (1.3.8)
Requirement already satisfied: cog in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.8.6)
Requirement already satisfied: imageio==2.19.3 in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (2.19.3)
Requirement already satisfied: imageio-ffmpeg==0.4.7 in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.4.7)
Requirement already satisfied: av in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (10.0.0)
Requirement already satisfied: torch-optimizer in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.3.0)
Requirement already satisfied: realesrgan in /Users/yaroslav/miniconda3/envs/myenv/lib/python3.10/site-packages (0.3.0)
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu
Installing dev requirements...

Unable to install requirements. This may be because one of your
requirements is invalid, or because pip was unable to connect
to the PyPI server.

**Comment by wladradchenko** [comment]
Did you do python -m pip install - r requirements.txt before briefcase dev? Anyway, you can comment line onnxruntime-gpu and uncomment onnxruntime.
