### ISSUE TITLE
Где посмотреть логи приложения?

### ISSUE THREAD

**Issue by LazarenkoA** [wladradchenko/wunjo.wladradchenko.ru#16]
Версия 1.5.4

Хотел воспользоваться функцией подмены лица на видео, выбрал фото (выбрал область лица), выбрал видео  (выбрал область лица), пошел процесс по итогу ошибка, только не понятно что за ошибка и где можно увидеть подробности. 
![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/15386101/69fe2d49-908d-45b5-b759-5cb42eb08fb3)

**Comment by wladradchenko** [comment]
> Версия 1.5.4
> 
> Хотел воспользоваться функцией подмены лица на видео, выбрал фото (выбрал область лица), выбрал видео  (выбрал область лица), пошел процесс по итогу ошибка, только не понятно что за ошибка и где можно увидеть подробности. 
> ![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/15386101/69fe2d49-908d-45b5-b759-5cb42eb08fb3)
> 

Привет. Вы используете Windows? Какая разрядность? Включали опцию улучшения лица? Если включали, попробуйте без неё, какой результат будет?

**Comment by LazarenkoA** [comment]
да Windows, разрядность 64. 

вот содержание окошка при выполнении "анимация лица и губ"

```
Error ... Unable to open C:\Users\Артем\.wunjo\deepfake\checkpoints\shape_predictor_68_face_landmarks.dat
Starting to crop and extract frames
File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\mapping_00109-model.pth.tar
File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\facevid2vid_00189-model.pth.tar
File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\auido2exp_00300-model.pth
File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\auido2pose_00140-model.pth
File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\wav2lip.pth
File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\hub.zip
File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\BFM_Fitting.zip
File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\epoch_20.pth
File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\shape_predictor_68_face_landmarks.dat
Processing will run on CPU
Пожалуйста, подождите... Обработка началась.
Command: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --user-data-dir=C:\Users\328F~1\AppData\Local\Temp\flaskwebgui --new-window --no-first-run --start-maximized --app=http://127.0.0.1:57296
```

**Comment by wladradchenko** [comment]
> да Windows, разрядность 64. 
> 
> вот содержание окошка при выполнении "анимация лица и губ"
> 
> ```
> Error ... Unable to open C:\Users\Артем\.wunjo\deepfake\checkpoints\shape_predictor_68_face_landmarks.dat
> Starting to crop and extract frames
> File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\mapping_00109-model.pth.tar
> File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\facevid2vid_00189-model.pth.tar
> File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\auido2exp_00300-model.pth
> File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\auido2pose_00140-model.pth
> File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\wav2lip.pth
> File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\hub.zip
> File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\BFM_Fitting.zip
> File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\epoch_20.pth
> File verified C:\Users\Артем\.wunjo\deepfake\checkpoints\shape_predictor_68_face_landmarks.dat
> Processing will run on CPU
> Пожалуйста, подождите... Обработка началась.
> Command: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --user-data-dir=C:\Users\328F~1\AppData\Local\Temp\flaskwebgui --new-window --no-first-run --start-maximized --app=http://127.0.0.1:57296
> ```
> 
> 

Понятно. Запрещает чтение моделей.  Вам нужно для каждой модели разрешетить доступ на чтение icacls "*.pth" /grant:r "Users":(R,W), вот видео как это делается https://youtu.be/2qIpJYhOL2U?feature=shared

**Comment by LazarenkoA** [comment]
не помогло, вот выполнил
![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/15386101/9d843f29-5de1-4dde-8440-8bdf7092bc0c)
ошибка та же. Дополнительно еще для *dat сделал, не помогло.
Может быть причиной то что в пути присутствует кириллица?

**Comment by wladradchenko** [comment]
> не помогло, вот выполнил
> ![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/15386101/9d843f29-5de1-4dde-8440-8bdf7092bc0c)
> ошибка та же. Дополнительно еще для *dat сделал, не помогло.
> Может быть причиной то что в пути присутствует кириллица? 

Выполните пожалуйста вот эту команду из директории .wunjo `icacls * /grant:r "Users:(R,W)" /T`. Ошибок в путях нет, иначе у меня на эмуляторе винды не работало бы))

**Comment by wladradchenko** [comment]
В любом случае вы можете изменить директорию папки .wunjo. Вам нужно открыть расположение программы, дойти до папки app\backend\folder.py и раскомитить строчку для задания кастомной директории .wunjo.

**Comment by LazarenkoA** [comment]
перенос .wunjo в другую директорию помог (процесс идет уже довольно долго), спасибо
