### ISSUE TITLE
Прошу помощи с компиляцией на apple silicon m2

### ISSUE THREAD

**Issue by exrector** [wladradchenko/wunjo.wladradchenko.ru#19]
Добрый день. 
Прошу поделиться развернутой инструкцией по установке на маки м2, тех, кто смог. Всей командой не можем одолеть. Заранее спасибо

**Comment by wladradchenko** [comment]
> Добрый день. 
> Прошу поделиться развернутой инструкцией по установке на маки м2, тех, кто смог. Всей командой не можем одолеть. Заранее спасибо

Привет. Такой версии Мака у меня нет, чтобы ее сделать. Однако, вот здесь аналогичная проблема была решена https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/14. Также, если вам не сложно, запишите видео установки на Мак с этим чипом для других пользователей.
