### ISSUE TITLE
Правки в wiki

### ISSUE THREAD

**Issue by jimdi** [wladradchenko/wunjo.wladradchenko.ru#20]
думаю стоит обновить немного вики, чтобы не было путаницы =)

в разделе по настройке GPU сразу указать страницу загрузки [NVIDIA CUDA Toolkit 11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive) раз она рекомендована для запуска, с актуальной 12.2 torch не работает

и в настройке виртуальной среды для Windows 
`venv\Scripts\activate.bat`
вместо 
`source venv/Script/activate`

**Comment by wladradchenko** [comment]
Обновлено
