### ISSUE TITLE
No GPU driver was found on your computer.

### ISSUE THREAD

**Issue by JeromeHumbert** [wladradchenko/wunjo.wladradchenko.ru#23]
Hello,

First I would like to thank you for this project, I have yet to make it fully fonctionnal. 

I tried to follow the wiki to configure the use of a GPU instead of the CPU but even after doing everything, I still get this error : 

Visit the documentation https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki to learn how to install drivers for your computer.
No GPU driver was found on your computer. Working on the GPU will speed up the generation of content several times.

I've done everything here : https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/How-to-use-the-GPU-in-the-application#windows-1

I got the "CUDA is available" message during the test. I'm not too sure what I can do more.

System specs : 
Windows 11
RTX 4090
Cuda 12.1
Python 3.10

Should i try with Cuda 11.8 ? 

Thank you in advance

**Comment by wladradchenko** [comment]
Hello. Yes. You need to try CUDA 11.8, because some neural network libs will not work with CUDA 12.1. https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/20
