### ISSUE TITLE
Предложения по проекту

### ISSUE THREAD

**Issue by BrasD99** [wladradchenko/wunjo.wladradchenko.ru#26]
Привет!

Я сейчас занимаюсь похожим проектом. Очень ждал твоей реализации клонирования голоса. Вижу, что ты остановился на https://github.com/CorentinJ/Real-Time-Voice-Cloning. На CPU данный проект работает очень медленно, результат очень слабый. Не рассматривал ли https://github.com/coqui-ai/TTS ? Мне понравились и скорость, и относительно хорошие результаты.

И касательно перевода текста, мне кажется, проще использовать обертку https://pypi.org/project/googletrans/ ;)

Но вот с клонированием голоса очень сложный вопрос. Хочется сделать что-то наподобие HeyGen, чтобы сохранялась интонация, тембр голоса. Я нашел https://mega-tts.github.io/demo-page/ с закрытым кодом. Мне кажется, нам надо двигаться в этом направлении. Идеальный дипфейк должен учитывать все особенности речи. Я продолжаю искать варианты, но пока что, увы, застрял на этом.

Если вдруг захочется обсудить то, к чему я пришел, можешь написать на brasd99@gmail.com, я собрал набор различных моделей, но ни одна из них, честно говоря, даже не близка к тому результату, что выдает HeyGen. А с нуля написать и обучить модель - мне на данный момент не хватит знаний.

Помимо этого я сейчас думаю над реализацией трекинга и реидентификации нескольких лиц. Чтобы пользователь мог перевести фильм в целом. Задача очень нетривиальная. Могу поделиться наработками.

**Comment by wladradchenko** [comment]
Привет. 

Не видел, что в проекте https://github.com/coqui-ai/TTS есть клонирование голоса. Однако сейчас я вряд ли буду вырезать целый модуль, чтобы начать эксперименты с другим подходом. Я планирую улучшить качество клонирования голоса как это сделано в HeyGen, это будет в версии 1.6.0 или 1.6.1, я клонирование голоса оставил на самое последнее.

На данный момент ведётся работа над изменением компонентов видео по текстовым подсказкам с полным контролем слоев и сглаживанием перехода кадров. Предположительно это будет лучше в качестве чем WarpFusion.

Для перевода я использую request с запросами в Google Translate, я стараюсь не ставить много лишний библиотек, если без этого можно обойтись, так как лимит для создания билда на Windows 2Гб, сейчас проект 1.85Гб.

**Comment by BrasD99** [comment]
По поводу TTS делюсь примером. Надеюсь, пригодится:
https://github.com/coqui-ai/TTS#example-text-to-speech-using-fairseq-models-in-1100-languages-

+ У них вышла XTTS, которую можно опробовать здесь: https://huggingface.co/spaces/coqui/xtts
Но на моих примерах с английской речью с озвучкой русского текста она выдала не очень хорошие результаты.

**Comment by wladradchenko** [comment]
По документации ими заявлено использование токена https://docs.coqui.ai/docs , а сами модели как понимаю работают на их серверах.

**Comment by BrasD99** [comment]
Веса модели загружаются локально. И она работает, соответственно, локально. При первом запуске она смотрит, загружена ли модель, название которой пробрасывается в аргументы конструктора. Если нет, то сначала загружает, а потом идет инференс на самом компьютере.

**Comment by BrasD99** [comment]
То, что ты прислал - документация для их API. Можно использовать и его. Но лично я предпочитаю не зависеть от их сервера и обрабатывать данные локально.

**Comment by BrasD99** [comment]
То, что ты прислал - документация для их API. Можно использовать и его. Но лично я предпочитаю не зависеть от их сервера и обрабатывать данные локально.

**Comment by wladradchenko** [comment]
@BrasD99 в любом случае, если появятся предложения в качестве коммитов для клонирования голоса, смело вносите. Недавно открыл под приложения [tg канал](https://t.me/wladblog) , где вы также можете писать, про баги, фидбэек и предложения, да и вообще, что хотите видеть в будущих версиях.

**Comment by BrasD99** [comment]
@wladradchenko Большое спасибо! На следующей неделе изучу код и попробую прислать пулл-реквест.
