### ISSUE TITLE
Windows. A matching Triton is not available

### ISSUE THREAD

**Issue by jimdi** [wladradchenko/wunjo.wladradchenko.ru#29]
if you get after `briefcase dev`
```
[wunjo] Starting in dev mode...
===========================================================================
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
```

you can fix this with this command:
`pip install https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl`

**Comment by wladradchenko** [comment]
Thanks. I will add in documentation for Windows GPU.

I can't sure what in pyproject.toml will work fine with pip install from huggingface.

**Comment by wladradchenko** [comment]
Yes. This can be used in pyproject.toml. I have updated file.
