### ISSUE TITLE
Mac os application won't start

### ISSUE THREAD

**Issue by kindmanspb** [wladradchenko/wunjo.wladradchenko.ru#30]
### Environment:

```
Date/Time:       2023-11-09 10:43:33 
Command line:    /Users/kindman/.pyenv/versions/3.10.13/bin/briefcase dev

OS Release:      Darwin 23.0.0
OS Version:      Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Architecture:    arm64
Platform:        macOS-14.0-arm64-arm-64bit

Python exe:      /Users/kindman/.pyenv/versions/3.10.13/bin/python3.10
Python version:  3.10.13 (main, Nov  8 2023, 10:20:57) [Clang 15.0.0 (clang-1500.0.40.1)]
Virtual env:     False
Conda env:       False

Briefcase:       0.3.16
Target platform: macOS
Target format:   None
```

### In dev mode:
`(venv)  kindman@MacBook-Pro  ~/WebstormProjects/wunjo.wladradchenko.ru/portable: briefcase dev`

```
[wunjo] Starting in dev mode...
===========================================================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kindman/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Users/kindman/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/kindman/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/kindman/WebstormProjects/wunjo.wladradchenko.ru/portable/src/wunjo/__main__.py", line 1, in <module>
    from wunjo.app import main
  File "/Users/kindman/WebstormProjects/wunjo.wladradchenko.ru/portable/src/wunjo/app.py", line 6, in <module>
    import torch
  File "/Users/kindman/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
ImportError: dlopen(/Users/kindman/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/_C.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_PyFrame_GetLasti'

Problem running app wunjo.
```

### Build & run mode:

```
[wunjo] Starting app...
===========================================================================
Configuring isolated Python...
Pre-initializing Python runtime...
PythonHome: /Users/kindman/WebstormProjects/wunjo.wladradchenko.ru/portable/build/wunjo/macos/app/Wunjo Wladradchenko AI.app/Contents/Resources/support/python-stdlib
PYTHONPATH:
- /Users/kindman/WebstormProjects/wunjo.wladradchenko.ru/portable/build/wunjo/macos/app/Wunjo Wladradchenko AI.app/Contents/Resources/support/python310.zip
- /Users/kindman/WebstormProjects/wunjo.wladradchenko.ru/portable/build/wunjo/macos/app/Wunjo Wladradchenko AI.app/Contents/Resources/support/python-stdlib
- /Users/kindman/WebstormProjects/wunjo.wladradchenko.ru/portable/build/wunjo/macos/app/Wunjo Wladradchenko AI.app/Contents/Resources/support/python-stdlib/lib-dynload
- /Users/kindman/WebstormProjects/wunjo.wladradchenko.ru/portable/build/wunjo/macos/app/Wunjo Wladradchenko AI.app/Contents/Resources/app_packages
- /Users/kindman/WebstormProjects/wunjo.wladradchenko.ru/portable/build/wunjo/macos/app/Wunjo Wladradchenko AI.app/Contents/Resources/app
Configure argc/argv...
Initializing Python runtime...
No Python NSLog handler found. stdout/stderr will not be captured.
To capture stdout/stderr, add 'std-nslog' to your app dependencies.
Running app module: wunjo
---------------------------------------------------------------------------
Application quit abnormally (Exit code -6)!
Traceback (most recent call last):
  File "Wunjo Wladradchenko AI.app/Contents/Resources/app/wunjo/__main__.py", line 1, in <module>
    from wunjo.app import main
  File "Wunjo Wladradchenko AI.app/Contents/Resources/app/wunjo/app.py", line 6, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by wladradchenko** [comment]
Hello!

From your message, it seems you might not have installed all the necessary dependencies. To address this, I recommend the following steps, especially if you're using a Mac where only the CPU version is compatible:

Install Dependencies: First, ensure you install the dependencies from requirements_cpu.txt. This file contains all the necessary packages for the CPU version of the application.

Modify Project Configuration: Next, in the portable folder, rename the configuration file for the CPU version:

```
mv pyproject_cpu.toml pyproject.toml
```

This step ensures that the project uses the correct settings for a CPU-based installation.

Skip briefcase dev: Instead of running briefcase dev, you can directly proceed with the following command:

```
briefcase build
```

This will build the application using the correct dependencies and configuration.

For more detailed instructions and troubleshooting tips, please refer to the documentation on our GitHub Wiki: [How to Install the Application](https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/How-to-install-the-application).

**Comment by kindmanspb** [comment]
@wladradchenko Да, это всё сделано, чётко следовал инструкциям. 
Дефолтный requirements.txt -> CPU, под него и ставил
`mv pyproject_cpu.toml pyproject.toml` -> делал

**Comment by wladradchenko** [comment]
> @wladradchenko Да, это всё сделано, чётко следовал инструкциям. Дефолтный requirements.txt -> CPU, под него и ставил `mv pyproject_cpu.toml pyproject.toml` -> делал

Установите в venv только briefcase и сделайте briefcase build, такой шаг минует briefcase dev и ошибки, которые могли быть допущены на этом шаге. У вас явное сообщение, что не установлен torch. Если вы сделали эти шаги, тогда провертье, что в venv появился torch и вы активировали venv `source venv/bin/activate`. 

Используйте PyCharm, он решает многие проблемы, которые могут возникнуть при не правильной настройки.

**Comment by kindmanspb** [comment]
@wladradchenko Thanks for pointing out the error. Fixed by installing **pyenv-virtualenv** and this comment https://github.com/pyenv/pyenv-virtualenv/issues/408#issuecomment-1644298267 

**Additionally, I note that there is a bug on m1:**

```
Traceback (most recent call last):
  File "/Users/kindman/WebstormProjects/wunjo.wladradchenko.ru/.venv/lib/python3.10/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

```
Fixed by upgrading in **requirements.txt** -> **soundfile=0.11.0** (m1 support)

Also encountered a bug with insightface: 
`Application source '../venv/lib/python3.10/site-packages/insightface' does not exist.`
(My venv directory has the name '.venv' but is not located with a dot) -> Fixed by renaming without a dot.

But now – briefcase build && briefcase run again failed with:

```
Application quit abnormally (Exit code -6)!
Traceback (most recent call last):
  File "Wunjo Wladradchenko AI.app/Contents/Resources/app/wunjo/__main__.py", line 1, in <module>
    from wunjo.app import main
  File "Wunjo Wladradchenko AI.app/Contents/Resources/app/wunjo/app.py", line 6, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by kindmanspb** [comment]
`briefcase dev` it freezes after:

```
[wunjo] Starting in dev mode...
===========================================================================
/Users/kindman/.wunjo/user_trained_voice/INSTRUCTION.md already exists!
/Users/kindman/.wunjo/user_trained_voice/custom_user.json already exists!
```

**Comment by wladradchenko** [comment]
> `briefcase dev` it freezes after:
> 
> ```
> [wunjo] Starting in dev mode...
> ===========================================================================
> /Users/kindman/.wunjo/user_trained_voice/INSTRUCTION.md already exists!
> /Users/kindman/.wunjo/user_trained_voice/custom_user.json already exists!
> ```

You are sure what it is freeze? Could u try open in browser 127.0.0.1:5000?

**Comment by wladradchenko** [comment]
> But now – briefcase build && briefcase run again failed with:

Do u have installed torch in your venv? If yes, than you can manually copy torch from your venv to build. Build in format app u can open as folder

**Comment by kindmanspb** [comment]
> > But now – briefcase build && briefcase run again failed with:
> 
> Do u have installed torch in your venv? If yes, than you can manually copy torch from your venv to build. Build in format app u can open as folder

I put in build but there was error with torch module "typing_extension" not found.

I restarted steps from zero and now on build another error:

```
ERROR: Could not find a version that satisfies the requirement insightface==0.7.3 (from versions: 0.2.1)
ERROR: No matching distribution found for insightface==0.7.3
Installing binary app requirements for x86_64...

Unable to install requirements. This may be because one of your
requirements is invalid, or because pip was unable to connect
to the PyPI server.

If an x86_64 wheel has not been published for one or more of your requirements,
you must compile those wheels yourself, or build a non-universal app by setting:

    universal_build = False

in the macOS configuration section of your pyproject.toml.
```
🥲 i'm unlucky?)

**Comment by kindmanspb** [comment]
On briefcase dev -> 403 Forbidden

**Comment by wladradchenko** [comment]
> On briefcase dev -> 403 Forbidden

Maybe u will try to use Virtual Box? I don't have Mac M+ to solve this trouble by comments, I need to have device to do this. I have Max Air 2017, abd this work on that Mac and build without problems.

For Windows or Linux for example I can rental server, for Mac I can not do something, maybe if somebody will share RDP connection with his Mac M+

**Comment by wladradchenko** [comment]
> <img width="744" alt="image" src="https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/121320234/0abad5a9-0ab8-40f1-a483-32b591fc2858">
> 

Hi. MacOS app work only on briefcase dev, you need to create venv and install requirements for MacOS. You don't need to do build, because MacOS on M+ chips has problem with briefcase build. In your case after build have not been copied torch in Mac app. 

Anyway, if u wanna to copy torch in build, u can do that by two way: copy all libs manually in built app or write in pyproject.toml path to venv/lib/torch witch u wanna copy in build from venv. I don't have MacOS with M+ to automate this way to create builds on MacOS, this reason why in documentation for MacOS wrote about briefcase dev only.

**Comment by leansii** [comment]
> > <img alt="image" width="744" src="https://private-user-images.githubusercontent.com/121320234/291307366-0abad5a9-0ab8-40f1-a483-32b591fc2858.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTEzNTQsIm5iZiI6MTcwMjkxMTA1NCwicGF0aCI6Ii8xMjEzMjAyMzQvMjkxMzA3MzY2LTBhYmFkNWE5LTBhYjgtNDBmMS1hNDgzLTMyYjU5MWZjMjg1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxNDUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDlkNjBmMGQ1YmM0MWQxN2Q1NTM1Nzk2MzFiODM4OTI2NDAzN2NmYjQ2Y2VmYjMxNWRhNmJlZDE2ZGUzMTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dQY3nocRwA2G6adudInYBOvxQ-8HtvRhS2haa3p13n8">
> 
> Hi. MacOS app work only on briefcase dev, you need to create venv and install requirements for MacOS. You don't need to do build, because MacOS on M+ chips has problem with briefcase build. In your case after build have not been copied torch in Mac app.
> 
> Anyway, if u wanna to copy torch in build, u can do that by two way: copy all libs manually in built app or write in pyproject.toml path to venv/lib/torch witch u wanna copy in build from venv. I don't have MacOS with M+ to automate this way to create builds on MacOS, this reason why in documentation for MacOS wrote about briefcase dev only.


for `briefcase dev`
<img width="759" alt="image" src="https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/121320234/23ad4daa-24dc-4005-9460-804942545c26">

**Comment by wladradchenko** [comment]
That looks like problem with Python on your MacOS. Have you installed Python3.10?

Anyway this is not relate to Wunjo AI and requirements, you need to solve this problem with your Python. You can try reinstall python and brew pandoc `brew uninstall pandoc` and `brew install pandoc`. Also you can install `pip install pypandoc`.

**Comment by NikitaTunes** [comment]
Using cached insightface-0.6.2.tar.gz (433 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/34/rrpdd3qs281bpfj3wjxvv4m00000gn/T/pip-install-7cjlvhle/insightface_7db6c4c76d384acbb0dc365a4decb255/setup.py", line 5, in <module>
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Installing dev requirements...

Unable to install requirements. This may be because one of your
requirements is invalid, or because pip was unable to connect
to the PyPI server.

How to resolve?

**Comment by wladradchenko** [comment]
Maybe `ModuleNotFoundError: No module named 'numpy'` install numpy? `python -m pip install numpy==1.23.5`.

**Comment by NikitaTunes** [comment]
> Maybe `ModuleNotFoundError: No module named 'numpy'` install numpy? `python -m pip install numpy==1.23.5`.

I have it installed already.
<img width="570" alt="Снимок экрана 2024-03-31 в 00 50 03" src="https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/163732434/8acddc66-71c2-4458-89df-0ec21c8714cf">

**Comment by wladradchenko** [comment]
I already see the error.  In the documentation, video and everywhere it is written that you must use only Python3.10, no other version of Python!
