### ISSUE TITLE
Faceswap over Videos gone Bad

### ISSUE THREAD

**Issue by OneNiNE87** [wladradchenko/wunjo.wladradchenko.ru#33]
in 1.6.2 the faceswap on videos looks like the model is back under training day 1.

**Comment by wladradchenko** [comment]
I didn't not change model for faceswap and this reason why quality cannot be changed by model.

**Comment by OneNiNE87** [comment]
> I didn't not change model for faceswap and this reason why quality cannot be changed by model. 

I will share a comparison once I switch back. Thanks for responding.
