### ISSUE TITLE
Обработка картинки, обращение к неиспользуемому диску

### ISSUE THREAD

**Issue by AndreyGrand** [wladradchenko/wunjo.wladradchenko.ru#36]
Выбрал картинку для удаления лишнего элемента и получаю ошибку
File "G:\AI\wunjo\src\app_packages\torch\nn\modules\module.py", line 1143, in convert
return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
File verified C:\Users\AndreyG\.wunjo\rtvc\ru\encoder.pt
Load RTVC encoder
Processing will run on GPU
Пожалуйста, подождите... Обработка началась.
Error ... D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 999: unknown error ; GPU=0 ; hostname=ANDREY ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=239 ; expr=cudaDeviceSynchronize();
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 999: unknown error ; GPU=0 ; hostname=ANDREY ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=239 ; expr=cudaDeviceSynchronize();

В моём случае диск D: я не использую, там стоит дистрибутив для linux.
Сам я загружаю Windows с диска C: а приложение установил на диск G:

**Comment by wladradchenko** [comment]
Привет. Видел такое раньше у себя в практике. У вас похоже CUDA не доступна. У меня есть с Nvidia CUDA на Ubuntu такой баг. Если я включаю компьютер, все нормально, работает, torch.cuda.is_available() будет показывать True, в любой программе с torch. Стоит мне компьютер перевести в спящий режим, возникает аналогичная ошибка, использования GPU больше не доступно, пока компьютер не будет перезагружен. Проблема с драйверами в Ubuntu, а может и во всем Linux. Если перезагрузка не решает ваши проблемы, тогда проверяйте nvidia-smi, что вы поставили правильно драйвера CUDA11.8, чтобы использовать приложение под GPU, иначе только переустановка. 
Я бы сказал, что это баг драйверов, а не приложения.
