### ISSUE TITLE
Where are said installers?

### ISSUE THREAD

**Issue by slaughters85j** [wladradchenko/wunjo.wladradchenko.ru#37]
This,

Install Wunjo AI

You can download installers for Windows, MacOS and Ubuntu operating systems on the official website [Wunjo AI](https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/wladradchenko.ru/wunjo).

would seem to indicate an installer is available to download, but no such installers are available.

Thanks

**Comment by wladradchenko** [comment]
Hello. Why is not. All installer are on official website witch you can find in about of project https://wladradchenko.ru/wunjo
