### ISSUE TITLE
No module named wunjo

### ISSUE THREAD

**Issue by Kedreamix** [wladradchenko/wunjo.wladradchenko.ru#44]
When use command briefcase run, I face with this problem. Can you help me?

[wunjo] Finalizing application configuration...
Targeting ubuntu:jammy (Vendor base debian)
Determining glibc version... done
Targeting glibc 2.35
Targeting Python3.10

[wunjo] Starting app...
===========================================================================
Install path: /root/AIGC/wunjo.wladradchenko.ru/portable/build/wunjo/ubuntu/jammy/wunjo-1.6.2/usr
Pre-initializing Python runtime...
PYTHONPATH:
- /usr/lib/python3.10
- /usr/lib/python3.10/lib-dynload
- /root/AIGC/wunjo.wladradchenko.ru/portable/build/wunjo/ubuntu/jammy/wunjo-1.6.2/usr/lib/wunjo/app
- /root/AIGC/wunjo.wladradchenko.ru/portable/build/wunjo/ubuntu/jammy/wunjo-1.6.2/usr/lib/wunjo/app_packages
Configure argc/argv...
Initializing Python runtime...
Running app module: wunjo
---------------------------------------------------------------------------
Application quit abnormally (Exit code -1)!
/root/miniconda3/envs/wj/bin/python3: No module named wunjo

Problem running app wunjo.

Log saved to /root/AIGC/wunjo.wladradchenko.ru/portable/logs/briefcase.2024_01_14-03_19_14.run.log

**Comment by Kedreamix** [comment]
It's my log
Date/Time:       2024-01-14 03:33:49
Command line:    /root/miniconda3/envs/wj/bin/briefcase run

OS Release:      Linux 5.15.0-91-generic
OS Version:      #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023
Architecture:    x86_64
Platform:        Linux-5.15.0-91-generic-x86_64-with-glibc2.35

Python exe:      /root/miniconda3/envs/wj/bin/python
Python version:  3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
Virtual env:     False
Conda env:       True

Briefcase:       0.3.16
Target platform: linux
Target format:   system

Environment Variables:
    CONDA_DEFAULT_ENV=wj
    CONDA_EXE=/root/miniconda3/bin/conda
    CONDA_PREFIX=/root/miniconda3/envs/wj
    CONDA_PREFIX_1=/root/miniconda3
    CONDA_PREFIX_2=/root/miniconda3/envs/py10
    CONDA_PROMPT_MODIFIER=(wj)
    CONDA_PYTHON_EXE=/root/miniconda3/bin/python
    CONDA_SHLVL=3
    CUDA_HOME=/usr/local/cuda
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
    DISPLAY=localhost:11.0
    HOME=/root
    LANG=en_US.UTF-8
    LD_LIBRARY_PATH=:/usr/local/cuda/lib64
    LESSCLOSE=/usr/bin/lesspipe %s %s
    LESSOPEN=| /usr/bin/lesspipe %s
    LOGNAME=root
    LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
    MOTD_SHOWN=pam
    OLDPWD=/root/AIGC/wunjo.wladradchenko.ru/portable/src
    PATH=/root/miniconda3/envs/wj/bin:/root/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/bin/ngc-cli:/usr/local/cuda/bin
    PWD=/root/AIGC/wunjo.wladradchenko.ru/portable
    SHELL=/bin/bash
    SHLVL=1
    SSH_CLIENT=223.74.34.13 22689 22
    SSH_CONNECTION=223.74.34.13 22689 64.176.215.21 22
    SSH_TTY=/dev/pts/9
    TERM=xterm
    USER=root
    XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
    XDG_RUNTIME_DIR=/run/user/0
    XDG_SESSION_CLASS=user
    XDG_SESSION_ID=321
    XDG_SESSION_TYPE=tty
    _=/root/miniconda3/envs/wj/bin/briefcase
    _CE_CONDA=
    _CE_M=

Briefcase Log:
[03:33:49]                                                                                                                                                             system.py:117
           [wunjo] Finalizing application configuration...                                                                                                             system.py:117
           Targeting ubuntu:jammy (Vendor base debian)                                                                                                                 system.py:127
           Determining glibc version... done                                                                                                                           system.py:185
           Targeting glibc 2.35                                                                                                                                        system.py:187
           Targeting Python3.10                                                                                                                                        system.py:191
                                                                                                                                                                          run.py:231
           [wunjo] Starting app...                                                                                                                                        run.py:231
                                                                                                                                                                   subprocess.py:711
           >>> Running Command:                                                                                                                                    subprocess.py:712
           >>>     /root/AIGC/wunjo.wladradchenko.ru/portable/build/wunjo/ubuntu/jammy/wunjo-1.6.2/usr/bin/wunjo                                                   subprocess.py:713
           >>> Working Directory:                                                                                                                                  subprocess.py:720
           >>>     /root                                                                                                                                           subprocess.py:721
           ===========================================================================                                                                                    run.py:160
           Install path: /root/AIGC/wunjo.wladradchenko.ru/portable/build/wunjo/ubuntu/jammy/wunjo-1.6.2/usr                                                       subprocess.py:681
           Pre-initializing Python runtime...                                                                                                                      subprocess.py:681
           PYTHONPATH:                                                                                                                                             subprocess.py:681
           - /usr/lib/python3.10                                                                                                                                   subprocess.py:681
           - /usr/lib/python3.10/lib-dynload                                                                                                                       subprocess.py:681
           - /root/AIGC/wunjo.wladradchenko.ru/portable/build/wunjo/ubuntu/jammy/wunjo-1.6.2/usr/lib/wunjo/app                                                     subprocess.py:681
           - /root/AIGC/wunjo.wladradchenko.ru/portable/build/wunjo/ubuntu/jammy/wunjo-1.6.2/usr/lib/wunjo/app_packages                                            subprocess.py:681
           Configure argc/argv...                                                                                                                                  subprocess.py:681
           Initializing Python runtime...                                                                                                                          subprocess.py:681
           Running app module: wunjo                                                                                                                               subprocess.py:681
           ---------------------------------------------------------------------------                                                                             subprocess.py:681
           Application quit abnormally (Exit code -1)!                                                                                                             subprocess.py:681
           /root/miniconda3/envs/wj/bin/python3: No module named wunjo                                                                                             subprocess.py:681
                                                                                                                                                                      __main__.py:40
           Problem running app wunjo.                                                                                                                                 __main__.py:41

Main thread traceback:
╭─────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────╮
│ /root/miniconda3/envs/wj/lib/python3.10/site-packages/briefcase/__main__.py:25 in main                                                                                           │
│                                                                                                                                                                                  │
│   22 │   │   command = Command(logger=logger, console=console)                                                                                                                   │
│   23 │   │   options = command.parse_options(extra=extra_cmdline)                                                                                                                │
│   24 │   │   command.parse_config(Path.cwd() / "pyproject.toml")                                                                                                                 │
│ ❱ 25 │   │   command(**options)                                                                                                                                                  │
│   26 │   except HelpText as e:                                                                                                                                                   │
│   27 │   │   logger.info()                                                                                                                                                       │
│   28 │   │   logger.info(str(e))                                                                                                                                                 │
│                                                                                                                                                                                  │
│ ╭───────────────────────────────────────────── locals ──────────────────────────────────────────────╮                                                                            │
│ │       command = <briefcase.platforms.linux.system.LinuxSystemRunCommand object at 0x7f5f7b1869b0> │                                                                            │
│ │       Command = <class 'briefcase.platforms.linux.system.LinuxSystemRunCommand'>                  │                                                                            │
│ │       console = <briefcase.console.Console object at 0x7f5f7b5be830>                              │                                                                            │
│ │             e = BriefcaseCommandError('Problem running app wunjo.')                               │                                                                            │
│ │ extra_cmdline = []                                                                                │                                                                            │
│ │        logger = <briefcase.console.Log object at 0x7f5f7b5be770>                                  │                                                                            │
│ │       options = {                                                                                 │                                                                            │
│ │                 │   'appname': None,                                                              │                                                                            │
│ │                 │   'update': False,                                                              │                                                                            │
│ │                 │   'update_requirements': False,                                                 │                                                                            │
│ │                 │   'update_support': False,                                                      │                                                                            │
│ │                 │   'update_resources': False,                                                    │                                                                            │
│ │                 │   'no_update': False,                                                           │                                                                            │
│ │                 │   'test_mode': False,                                                           │                                                                            │
│ │                 │   'passthrough': []                                                             │                                                                            │
│ │                 }                                                                                 │                                                                            │
│ │        result = 200                                                                               │                                                                            │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                            │
│                                                                                                                                                                                  │
│ /root/miniconda3/envs/wj/lib/python3.10/site-packages/briefcase/commands/run.py:302 in __call__                                                                                  │
│                                                                                                                                                                                  │
│   299 │   │                                                                                                                                                                      │
│   300 │   │   self.verify_app(app)                                                                                                                                               │
│   301 │   │                                                                                                                                                                      │
│ ❱ 302 │   │   state = self.run_app(                                                                                                                                              │
│   303 │   │   │   app,                                                                                                                                                           │
│   304 │   │   │   test_mode=test_mode,                                                                                                                                           │
│   305 │   │   │   passthrough=[] if passthrough is None else passthrough,                                                                                                        │
│                                                                                                                                                                                  │
│ ╭───────────────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────────────╮                                             │
│ │                 app = <wladradchenko.ru.wunjo v1.6.2 AppConfig>                                                                  │                                             │
│ │             appname = None                                                                                                       │                                             │
│ │         binary_file = PosixPath('/root/AIGC/wunjo.wladradchenko.ru/portable/build/wunjo/ubuntu/jammy/wunjo-1.6.2/usr/bin/wunjo') │                                             │
│ │           no_update = False                                                                                                      │                                             │
│ │             options = {}                                                                                                         │                                             │
│ │         passthrough = []                                                                                                         │                                             │
│ │                self = <briefcase.platforms.linux.system.LinuxSystemRunCommand object at 0x7f5f7b1869b0>                          │                                             │
│ │               state = None                                                                                                       │                                             │
│ │       template_file = PosixPath('/root/AIGC/wunjo.wladradchenko.ru/portable/build/wunjo/ubuntu/jammy')                           │                                             │
│ │           test_mode = False                                                                                                      │                                             │
│ │              update = False                                                                                                      │                                             │
│ │ update_requirements = False                                                                                                      │                                             │
│ │    update_resources = False                                                                                                      │                                             │
│ │      update_support = False                                                                                                      │                                             │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                                             │
│                                                                                                                                                                                  │
│ /root/miniconda3/envs/wj/lib/python3.10/site-packages/briefcase/platforms/linux/system.py:805 in run_app                                                                         │
│                                                                                                                                                                                  │
│    802 │   │   )                                                                                                                                                                 │
│    803 │   │                                                                                                                                                                     │
│    804 │   │   # Start streaming logs for the app.                                                                                                                               │
│ ❱  805 │   │   self._stream_app_logs(                                                                                                                                            │
│    806 │   │   │   app,                                                                                                                                                          │
│    807 │   │   │   popen=app_popen,                                                                                                                                              │
│    808 │   │   │   test_mode=test_mode,                                                                                                                                          │
│                                                                                                                                                                                  │
│ ╭──────────────────────────────────────────── locals ─────────────────────────────────────────────╮                                                                              │
│ │         app = <wladradchenko.ru.wunjo v1.6.2 AppConfig>                                         │                                                                              │
│ │   app_popen = <Popen: returncode: 1 args: ['/root/AIGC/wunjo.wladradchenko.ru/portable/bui...>  │                                                                              │
│ │      kwargs = {}                                                                                │                                                                              │
│ │ passthrough = []                                                                                │                                                                              │
│ │        self = <briefcase.platforms.linux.system.LinuxSystemRunCommand object at 0x7f5f7b1869b0> │                                                                              │
│ │   test_mode = False                                                                             │                                                                              │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                              │
│                                                                                                                                                                                  │
│ /root/miniconda3/envs/wj/lib/python3.10/site-packages/briefcase/commands/run.py:190 in _stream_app_logs                                                                          │
│                                                                                                                                                                                  │
│   187 │   │   │   │   # If we're monitoring an actual app (not just a log stream),                                                                                               │
│   188 │   │   │   │   # and the app didn't exit cleanly, surface the error to the user.                                                                                          │
│   189 │   │   │   │   if popen.returncode != 0:                                                                                                                                  │
│ ❱ 190 │   │   │   │   │   raise BriefcaseCommandError(f"Problem running app {app.app_name}.")                                                                                    │
│   191 │   │                                                                                                                                                                      │
│   192 │   │   except KeyboardInterrupt:                                                                                                                                          │
│   193 │   │   │   pass  # Catch CTRL-C to exit normally                                                                                                                          │
│                                                                                                                                                                                  │
│ ╭───────────────────────────────────────────── locals ─────────────────────────────────────────────╮                                                                             │
│ │          app = <wladradchenko.ru.wunjo v1.6.2 AppConfig>                                         │                                                                             │
│ │ clean_filter = None                                                                              │                                                                             │
│ │ clean_output = False                                                                             │                                                                             │
│ │  exit_filter = <function LogFilter.test_filter.<locals>.filter_func at 0x7f5f79bb2950>           │                                                                             │
│ │   log_filter = <briefcase.commands.run.LogFilter object at 0x7f5f79bddc30>                       │                                                                             │
│ │   log_stream = False                                                                             │                                                                             │
│ │        popen = <Popen: returncode: 1 args: ['/root/AIGC/wunjo.wladradchenko.ru/portable/bui...>  │                                                                             │
│ │         self = <briefcase.platforms.linux.system.LinuxSystemRunCommand object at 0x7f5f7b1869b0> │                                                                             │
│ │    stop_func = <function RunAppMixin.<lambda> at 0x7f5f79d2b910>                                 │                                                                             │
│ │    test_mode = False                                                                             │                                                                             │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                             │
╰────────────────────────────────────────────────

**Comment by wladradchenko** [comment]
Hello. I see that you use miniconda3. I wrote in [documentation](https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/How-to-use-the-GPU-in-the-application) what need to use `python3.10 -m venv venv` in project folder. I didn't support other approaches to run. Because of briefcase uses specific run from folder where is pyproject.toml and specific code links.
