### ISSUE TITLE
в readme отсутствуют часть изображений

### ISSUE THREAD

**Issue by jimdi** [wladradchenko/wunjo.wladradchenko.ru#47]
https://github.com/wladradchenko/wunjo.wladradchenko.ru?tab=readme-ov-file#face-animation-from-image-src - правого изображения нет

https://github.com/wladradchenko/wunjo.wladradchenko.ru?tab=readme-ov-file#face-animation-from-image-src - все три не загружаются

https://github.com/wladradchenko/wunjo.wladradchenko.ru?tab=readme-ov-file#retouch-ai-to-improve-quality-of-deepfake - оба отсутствуют

**Comment by wladradchenko** [comment]
Привет. Всё нормально загружается

**Comment by jimdi** [comment]
оооочень долгое, почему-то. проверял в разных браузерах

может попробовать перезалить? или сложить в репу?
![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/2002983/71c66bb0-2d3e-4710-bafb-a6d58749aca7)

**Comment by wladradchenko** [comment]
Потому что gif и для GitHub это уже много. Gif потому что демонстрация различных возможностей. Можно что-то сделать? Да, но зачем, это только обёртка редми, и не относится к приложению))

**Comment by jimdi** [comment]
> Можно что-то сделать?

да, думаю в mp4 лучше или в gifv сконвертить и пережать. если некогда, то могу помочь поэкспериментировать - результатами поделюсь =)

**Comment by wladradchenko** [comment]
Mp4 я пробовал, мне наоборот это больше не нравится чем gif. Спасибо за предложение, но я не хочу менять редми))
