### ISSUE TITLE
после выполнения briefcase build нет app_packages в сборке

### ISSUE THREAD

**Issue by jimdi** [wladradchenko/wunjo.wladradchenko.ru#48]
тестировал под win11
Python 3.10.11

в том же venv `briefcase dev` запускает проект и всё работает ок

**Comment by wladradchenko** [comment]
Привет. На [YouTube](https://youtu.be/fucxKhX7n4E?feature=shared) вышло видео о сборке. Сборка работает на Win11 и Win10. Следуйте шагам видео или документации, если возникли проблемы.

**Comment by jimdi** [comment]
делал всё как указано, но после `briefcase build` в `portable\build\wunjo\windows\app\src\app_packages` пусто. 
на видео в этой директории различные пакеты имеются.

**Comment by wladradchenko** [comment]
Странно. Такого не встречал. Скачайте Wunjo AI Portable и скопируйте все библиотеки из той папки app_packages.
