### ISSUE TITLE
download model manually 

### ISSUE THREAD

**Issue by MadeByKit** [wladradchenko/wunjo.wladradchenko.ru#49]
hey, instead of making it download model automatically,, why dont you just provide the model links and also explain what folder we will input it into....

downloading it automatically can be stressful at times when it failed and you need to restart

**Comment by wladradchenko** [comment]
You can find a video how download manually on YouTube channel 23:10 or documentation or telegram smart bot.

Also u can subscribe on YouTube channel and say what is new videos u wanna see about Wunjo.

Please. Don't need to open duplicate [issues](https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/50).
