### ISSUE TITLE
checkpoint & config file

### ISSUE THREAD

**Issue by MadeByKit** [wladradchenko/wunjo.wladradchenko.ru#50]
Error ... This checkpoints is not found in config file. Update config file via internet! For more details, visit our documentation: https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki

why dont you make the checkpoint and models available for manual download

**Comment by wladradchenko** [comment]
You can find a video how download manually on [YouTube channel](https://youtu.be/00gzOC_cw9Y?feature=shared) or documentation or telegram smart bot.
