### ISSUE TITLE
Please specify that this project is using inswapper_128.onnx for face swapping.

### ISSUE THREAD

**Issue by nttstar** [wladradchenko/wunjo.wladradchenko.ru#54]

**Comment by wladradchenko** [comment]
Hello.  I don't understand the content of the question.  If the question is about how the face swap approach works, then I made a video about it on [YouTube](https://youtu.be/8jTKuA2HX8s).

**Comment by nttstar** [comment]
The actual name of your faceswap.onnx is inswapper_128.onnx, from the InsightFace project(which you can google it). I noticed that you've credited many open-source projects but did not mention inswapper_128, and renaming it to faceswap.onnx struck me as quite odd.

**Comment by wladradchenko** [comment]
There were quite a lot of projects for each module, some of which I taught and completely rewrote.  Redmi itself has changed and been downsized many times.  The video talks about all the approaches and neural networks, in fact it is a reminder.  At the moment, I don’t remember why there is something in Redmi, and something not, maybe I got laid off, maybe I changed a lot and there’s practically nothing left from the original approach.

All approaches and libraries that are used under the MIT license.

**Comment by nttstar** [comment]
Face swapping is one of the core features of your project, as can be seen from the sample images in the About section of your README. You also credit many third-party open-source models you used in the Credits section, but you're missing a reference to this most important face swapping model. Additionally, you have removed the original filename inswapper_128 and renamed it to the more neutral faceswap.onnx. No matter how you look at it, it seems a bit odd. Regardless of how many modifications you've made, please acknowledge in the Credits section that your face swapping model comes from the InsightFace project's inswapper_128 model.
