### ISSUE TITLE
Unable to find Community edition installer for Windows

### ISSUE THREAD

**Issue by nitinmukesh** [wladradchenko/wunjo.wladradchenko.ru#55]
Hello,

I navigated to the site as mentioned and landed at the following site
https://boosty.to/wunjo

But unable to find any installer download link on the page

**Comment by wladradchenko** [comment]
Hi. I updated the Community Edition code yesterday and have not yet built the installers. To build the installer, I need to rent a virtual machine with Windows, so I will do that later. However, you have three options: I recorded a [video](https://youtu.be/00gzOC_cw9Y?feature=shared) on how to build the installer or app, or you try now Pro version with full functionality (7 days trial and cost for a year by price the cup of coffee), or download the installers of version 1.6.
