### ISSUE TITLE
faceswap

### ISSUE THREAD

**Issue by zachysaur** [wladradchenko/wunjo.wladradchenko.ru#56]
on your faceswap example with faceswap how you changed color of body wit swaped face if you can explain

**Comment by wladradchenko** [comment]
Hello. Yes, of course. You need to open the restyling video panel, select the object you need, a object segment by time. Next, a simple prompt, what girl and what skin color or nationality. For best result, I recommend min 16 VRAM for restyle. 

After processing, I have opened the face swap to generate the necessary face in the generator, and replace it. Then we click on the burger and proceed to enhance the face quality. And here is the result ready.

**Comment by zachysaur** [comment]
this only work with video not picture?

**Comment by zachysaur** [comment]
You need to open the restyling video panel how i can open that i cant find it

**Comment by wladradchenko** [comment]
This work with video (mp4) and image (png, jpg, jpeg).

**Comment by wladradchenko** [comment]
> You need to open the restyling video panel how i can open that i cant find it

In video you can see information about [restyle](https://youtu.be/-MGow5zCZUQ?feature=shared). Restyle in Pro version from wunjo.online, but on Boosty users can vote which modules will be migrate from Pro to Community Edition.

I have decided on the following approach: all new features are initially released in the Professional version. However, if people vote, support author's work, acknowledge the author's sleepless nights, and request the specific feature's code to be open-sourced and incorporated into the Community Edition, I am willing to accommodate. Here is the [Boosty](https://boosty.to/wunjo) page: if a particular feature garners 20 votes, such as video restyling, I will transfer it to the community edition. Subsequently, a new vote will be initiated for speech cloning and additional features.

**Comment by zachysaur** [comment]
i am a youtuber i know peoples are dying for this feature if you allow me
to have it i can contribute to authors work and have peoples subscribe his
boosty i am actually going to post a video about how to install this
amazing tool and its features

**Comment by wladradchenko** [comment]
Thank you.  I promise that any feature that gets enough votes on Boosty will be added to the Community Edition.  In the near future I will add installers for the Community Edition version on Boosty.  And the video restyling function will be further improved to controlled restyling of videos and objects.

**Comment by zachysaur** [comment]
i also make portable version and got boosty account i used to have patreon but i find out they are frauds i got a question after how many days boosty pay you your income?

**Comment by wladradchenko** [comment]
The balance accumulated per day is withdrawn automatically after the day changes.  Some payments are verified.  This is necessary to protect Busti users from scammers.  Due to additional manipulations, the payment period may increase up to 5 days.

**Comment by zachysaur** [comment]
i made my account yesterday around this time i made 100$ and 4 subs i havnt received anthing if  they saying everyday
