### ISSUE TITLE
briefcase dev error

### ISSUE THREAD

**Issue by myprivacygithub** [wladradchenko/wunjo.wladradchenko.ru#57]
![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/125949094/b508a1b5-f052-4f35-b4c5-3d848b73ccc8)

**Comment by wladradchenko** [comment]
Hi. This looks like you have installed requirements in global python, not in venv. You need to install requirements in venv with python3.10.  Also you can try manually removed briefcase from folder which you see on screen.

**Comment by myprivacygithub** [comment]
thank you quick response, will correct the installation.
