### ISSUE TITLE
Lip Sync file save error - No such file or directory

### ISSUE THREAD

**Issue by myprivacygithub** [wladradchenko/wunjo.wladradchenko.ru#58]
![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/125949094/e3707048-e5e7-4f55-abda-dac4b617ea92)

**Comment by wladradchenko** [comment]
Hi. What is version of app?

**Comment by myprivacygithub** [comment]
i didn't enable overlay, in the tmp folder multiple files are there. separate audio and video files, but merged file is not there

**Comment by wladradchenko** [comment]
As I wrote in another issue.  You have problems with ffmpeg.  Complete the correct installation of the program (without comda) and ffmpeg for your computer in os environment.
