### ISSUE TITLE
face swap image FFMPEG error

### ISSUE THREAD

**Issue by myprivacygithub** [wladradchenko/wunjo.wladradchenko.ru#59]
![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/125949094/826fddac-fbb5-4a9b-8b89-47e6a3d8b38d)

**Comment by myprivacygithub** [comment]
![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/125949094/ff11f809-0289-4b96-be88-cf12303a04f9)
![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/125949094/4ab4c3e2-966c-4156-ab74-ec155477e27d)
swapped image is there in tmp folder, but this error is coming, why? also how to config save path?

**Comment by myprivacygithub** [comment]
also UI is always showing BUSY
![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/125949094/52def54b-598d-4e90-8e29-bc919d555a55)

**Comment by wladradchenko** [comment]
All these issues are related to ffmeg. Did you install it yourself or did it install automatically? Anyway without describe problem, I don't understand steps which related to issue.

In any case, the errors are not related to the program, and I cannot help with them. Please check what problems you have with ffmpeg, what drivers are missing for video playback. 

Try the Pro version (wunjo.online) or wait for me to create an installer. 

I saw a video where Anaconda was used for installation, which is incorrect. The entire installation process is described on the Wiki [page](https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/How-to-use-the-GPU-in-the-application) and [video](https://youtu.be/00gzOC_cw9Y?feature=shared). Do not use Anaconda, as it may cause errors. 

In first run in folder .wunjo will be installed right version of ffmpeg https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip.  You need to check what is version compatible with your computer.
