### ISSUE TITLE
don't function normally, 

### ISSUE THREAD

**Issue by departurechen** [wladradchenko/wunjo.wladradchenko.ru#60]
D:\wunjo\wunjo\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[SERVER][INFO][2024-06-25 01:40:57] http://127.0.0.1:8000
[SERVER][INFO][2024-06-25 01:40:57] http://127.0.0.1:8000/console-log
[ERROR:0@0.004] global cap_ffmpeg_impl.hpp:1268 open Could not find decoder for codec_id=61
[ERROR:0@0.004] global cap_ffmpeg_impl.hpp:1317 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
[ WARN:0@152.498] global loadsave.cpp:241 cv::findDecoder imread_('C:\Users\admin\.wunjo\tmp\%01db82334f-5fcc-4f5c-b65a-48fdd4cdab9a.jpg'): can't open/read file: check file path/integrity
[ERROR:0@0.407] global cap_ffmpeg_impl.hpp:1268 open Could not find decoder for codec_id=61
[ERROR:0@0.407] global cap_ffmpeg_impl.hpp:1317 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
[ WARN:0@152.802] global loadsave.cpp:241 cv::findDecoder imread_('C:\Users\admin\.wunjo\tmp\%01db82334f-5fcc-4f5c-b65a-48fdd4cdab9a.jpg'): can't open/read file: check file path/integrity
![112](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/131435447/7481776d-8961-4edc-a256-740df9ec474f)

**Comment by wladradchenko** [comment]
Hi. I asked how solve this problem with ffmpeg in this [issue](https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/59). Short answer: please, use wiki documentation and video how install Wunjo GPU, not use conda and add ffmpeg in os environment with your win32 or win64 system. I don’t use it when, and therefore I can’t say anything about it.  I know there may be mistakes with ffmpeg.

**Comment by wladradchenko** [comment]
Also you can use Wunjo Pro installer from wunjo.online or waiting for while I will build installer for CE version.

**Comment by departurechen** [comment]
thanks a million

**Comment by departurechen** [comment]
I uninstalled ffmpeg, and download from: https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip. add path to ffmpeg in os enviroment for Windows, error still exists:

D:\wunjo\wunjo\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[SERVER][INFO][2024-06-25 19:02:10] http://127.0.0.1:8000
[SERVER][INFO][2024-06-25 19:02:10] http://127.0.0.1:8000/console-log
[ERROR:0@0.012] global cap_ffmpeg_impl.hpp:1268 open Could not find decoder for codec_id=61
[ERROR:0@0.012] global cap_ffmpeg_impl.hpp:1317 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
[ WARN:0@22.710] global loadsave.cpp:241 cv::findDecoder imread_('C:\Users\admin\.wunjo\tmp\%03def8fb-5176-42ba-8bed-5b6e1efd0464.jpg'): can't open/read file: check file path/integrity

**Comment by wladradchenko** [comment]
maybe you show not full message? Please, click on name Error, and download log to attach its in message

**Comment by departurechen** [comment]
[console_log_2024-06-25T13_14_31.162Z.log](https://github.com/user-attachments/files/15971945/console_log_2024-06-25T13_14_31.162Z.log)

**Comment by wladradchenko** [comment]
Great. If you open log, you can see message: "Model not found and this application cannot access to internet". So, you need to allow Wunjo through your firewall or download models manually. All models link and path where need to download you will find in settings page.

**Comment by departurechen** [comment]
I disabled firewall,still not working. Can you guide me step by step? what should I do next?

**Comment by wladradchenko** [comment]
The fire meter should not be turned off, it is not safe.  Just add the application to the exceptions.  And it’s quite difficult to do this if it’s not done the first time you start it.

I don't have instructions for the firewall on Windows.  I can only recommend figuring it out yourself or downloading all the models manually for the modules you need, more details on the settings page.  Don't forget to disable checking the integrity of models over the Internet in the Wunjo application for mannualy download models, since you initially limited access to the Internet.

**Comment by departurechen** [comment]
I don't know how to download all the models automatically?

**Comment by wladradchenko** [comment]
To install models automatically, you need to allow the application access to the Internet through the firewall, turn on the Internet and launch a module.  upon first launch, the necessary models will be downloaded automatically

**Comment by wladradchenko** [comment]
Try to remove Wunjo CE (also manually remove Wunjo folder) and .wunjo folder. Download and install Wunjo Pro. Allow to software use internet for firewall. Wunjo Pro has another signature and firewall can repeat ask about using internet.

**Comment by departurechen** [comment]
I downloaded the Wunjo Pro,failed to run it,  thanks anyway.
