### ISSUE TITLE
GPU Doesn't Work

### ISSUE THREAD

**Issue by RFedz007989** [wladradchenko/wunjo.wladradchenko.ru#61]
Hi,

Hope you are doing Good.
Inspite of all the GPU Installations, still it occupies full 100% CPU.

Can you pls assist on this...

Thank You

**Comment by wladradchenko** [comment]
Hi. In settings page you can see option change gpu on cpu or back. Can you check that gpu is active?

Also, GPU work for modules, but tasks as Segment Objects for frontend, Analysis content on fake, will be work only on CPU, if you use this.

**Comment by RFedz007989** [comment]
> Hi. In settings page you can see option change gpu on cpu or back. Can you check that gpu is active?
> 
> Also, GPU work for modules, but tasks as Segment Objects for frontend, Analysis content on fake, will be work only on CPU, if you use this.

Thanks. Can you pls check the attachment.
![Settings](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/158298313/925ebadc-5dfd-4830-9b48-1861b85b2685)

Thank You

**Comment by wladradchenko** [comment]
You need to click on "Which processor I need to use?".

**Comment by wladradchenko** [comment]
Also, I see what you use Pro Wunjo. Can you open restyle or you see message what gpu is not access for computer?

**Comment by RFedz007989** [comment]
I checked restyle It occupies 100% full CPU

**Comment by RFedz007989** [comment]
> You need to click on "Which processor I need to use?".

I clicked here. Here It states (In GPU mode, models are executed using the GPU for enhanced performance. If you wish to give the machine a break, you can transfer the models back to the CPU by clicking here. Remember, you can only switch processors when there is no active processing.)

Now what to do next...

**Comment by wladradchenko** [comment]
If the restyle operation was successful, it proves that the GPU is functioning, as there is a module that does not work on the CPU. It is important to note that working on the GPU accelerates processing several times but does not fully occupy your GPU processor, and does not relieve the CPU processor of its duties. Since there are simple operations like video cropping and frame saving, all of this is done using OpenCV and ffmpeg, which utilize the CPU and this can be 100%.

**Comment by RFedz007989** [comment]
Thanks, but I was using Faceswap even here also CPU occupied was 100% & GPU was 0.3%

**Comment by wladradchenko** [comment]
It's similar there.  Absolutely all modules do not store many frames in RAM, but save from and load when necessary.  This approach allowed people who have little RAM to use the application and work with very long videos.  By the way, I recommend studying the settings, there are many parameters that you can customize for yourself, for example, to work with a large number of tasks, adjusting memory, video duration, etc.

**Comment by RFedz007989** [comment]
OK, Thanks & Sorry for bothering you
