### ISSUE TITLE
task success but error in logs

### ISSUE THREAD

**Issue by akwin1234** [wladradchenko/wunjo.wladradchenko.ru#62]
[console_log_2024-06-29T18_17_35.125Z.log](https://github.com/user-attachments/files/16041818/console_log_2024-06-29T18_17_35.125Z.log)
Please check what is problem

![image](https://github.com/wladradchenko/wunjo.wladradchenko.ru/assets/15890770/0da0ae61-4f6f-4781-9604-d33b172f7107)

**Comment by wladradchenko** [comment]
Hi.

I see in log file message:

```
0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/2 [00:00<?, ?it/s]
[SERVER][INFO][127_0_0_1][2024-06-29 23:46:27] [Lip sync] Lip sync started.
[SERVER][INFO][127_0_0_1][2024-06-29 23:46:27] [Lip sync] Face detection started.
```

This means what detection of face started, but you can see what nothing was found. You can use media from [example](https://github.com/wladradchenko/wunjo.wladradchenko.ru/tree/main/example/test) to make sure  what Wunjo is installed (or build) correctly.
