### ISSUE TITLE
briefcase dev

### ISSUE THREAD

**Issue by Cal-DCosta** [wladradchenko/wunjo.wladradchenko.ru#66]
Installation went fine no issues but when briefcase dev is run then it hangs trying to get triton==2.0.0

**Comment by wladradchenko** [comment]
Hi. Did you use the [documentation](https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/How-to-use-the-GPU-in-the-application) or [video](https://youtu.be/00gzOC_cw9Y?feature=shared) during installation? Does the program work without Triton or is it just an indication that it is missing and everything else works?

This [issue](https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/29) about solution.

**Comment by Cal-DCosta** [comment]
I used both as there were other dependencies I needed, it was just stuck on triton, I also noticed that it reinstalled torch, torchvision and torchaudio before going onto triton, I wonder if the briefcase is reinstalling already installed dependencies. Anyway I got frustrated and deleted the install and the directory was worth the try.

**Comment by wladradchenko** [comment]
In Boosty https://boosty.to/wunjo you will find installer on Windows and Ubuntu. Also you can see what in documentation (1) install requirements_gpu, (2) install torch, torchvision, torchaudio again and (3) install xforms witch use triton. Also you can try to install firsly triton and after install all requirements.
