### ISSUE TITLE
wunjo ai v2 zluda

### ISSUE THREAD

**Issue by brcisna** [wladradchenko/wunjo.wladradchenko.ru#68]
Debian 13 

trying to get wunjo v2 to work with zluda backend

have symlinked zluda directory to wunjo directory
copied the the three zluda files to torch/libs dir on the venv
use the following command as suggested on zluda github to start breifcase dev   ( for Linux) 

LD_LIBRARY_PATH="<ZLUDA_DIRECTORY>:$LD_LIBRARY_PATH" <APPLICATION> <APPLICATION_ARGUMENTS>

I dont understand when i go into settings on wunjo,,i do not have option for GPU usage?
I seen the snippet about launching google-chome with a  command to enable gpu,,,but that always just says 'site not found'
Can anyone give better details on this particular command. I dont understand how the command that was shown can launch an instance of wunjo?

TIA

**Comment by wladradchenko** [comment]
Hi. You need to add in the [app.py](https://github.com/wladradchenko/wunjo.wladradchenko.ru/blob/main/portable%2Fsrc%2Fwunjo%2Fapp.py) file the line 11 `print(torch.cuda.is_available())` , to know whether working with CUDA is available when using your ZLUDA.

I think there is no need to open new topics separately from the [question](https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/65), if they are interconnected, it will be more difficult for users to navigate.

**Comment by brcisna** [comment]
@wladradchenko 

Success!
With adding this extra lines i could see no devices being found. Was a lot of rooting around trying to find out why.
Purely by accident it hit me i needed to install pytorch with ROCm!!!

As an aside comfyUI was showing no Nvidia device detected as well.
So,,, i found a link for the right commanr for pytoch with ROCm

In wunjo i done pip uninstall torch torchaudio torchvision
Then I done 

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.0

wunjo now detected a GPU device !!
But i got this error 
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor

SO,,, done this:
Open ,,,,,,,/venv/lib/python3.10/site-packages/basicsr/data/degradations.py and on line 8, simply change:

from torchvision.transforms.functional_tensor import rgb_to_grayscale
to:

from torchvision.transforms.functional import rgb_to_grayscale

![wunjo_gpu](https://github.com/user-attachments/assets/b364ef81-f985-4a2a-bab3-947b6ca52fde)


I think i may be able to get Zluda working now
Will report

Also,,,, You should make a note for AMD GPU users,,,to do the same,,
IE: remove torch torchvision torchaudio
Then pip install torch with rocm.
Also,,,the edit i hafd to do,,i think,,is fixed in later versions of torch-rocm...
I remember having to do this edit,,,a year ago,,,when i first started into this journey>
Thanks for the help

**Comment by wladradchenko** [comment]
@brcisna Nice to hear that it worked for you. Good job.
