### ISSUE TITLE
generations errors

### ISSUE THREAD

**Issue by brcisna** [wladradchenko/wunjo.wladradchenko.ru#69]
Debian 13
using Python-3.10.12 venv
AMD Radeon Pro W6600 (8GB) 
pytorch with rocm

When using just the default text prompt in the Generation tab,,,,,it runs for several minutes,,then eventually shows "ERROR" in red upper left,
Have tried with a few different small resolution photos also.,
I see nothing in the log directory
How to troubleshoot?
It appears all other items are working fine.

TIA

**Comment by wladradchenko** [comment]
Did you return debug true on false in app.py?

If debug false.  In order to see loading status and detail log, you need click on Wunjo, that you will see log in real time and also can download ones

If debug true, you will see all information in console.

**Comment by brcisna** [comment]
@wladradchenko 

After setting debug=true, this is error in cnsole/ log/ Pretty sure it has something to do xformers from doing a google search,,,,but,,not smart enough to figure out what needs to be changed.

Something worth noting when i install pytorch for rocm i wound up with pytoch 2.4.x so xformers isa  much newer version than what is in the wunjo requirments
Im noit sure how to try removing then install an older version of pytorch with rocm integrated.
Kind of a mixed up mess,,from my viewpoint.

Console:

[SERVER][INFO][127_0_0_1][2024-09-20 08:30:44] [Outpaint] Processing.
/home/superuser/.pyenv/versions/wunjo/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
[SERVER][ERROR][127.0.0.1][2024-09-20 08:30:52] No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`ckF` is not supported because:
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    
    TIA

**Comment by wladradchenko** [comment]
I think you right, this relates to xformers because of memory_efficient_attention_forward I found only in `xformers/ops/__init__.py` as import from .fmha. 

You need to downgrade xformers to 0.0.19 or add memory_efficient_attention_forward method:

```
def _memory_efficient_attention_forward(
    inp: Inputs, op: Optional[Type[AttentionFwOpBase]]
) -> torch.Tensor:
    inp.validate_inputs()
    output_shape = inp.normalize_bmhk()
    if op is None:
        op = _dispatch_fw(inp)
    else:
        _ensure_op_supports_or_raise(ValueError, "memory_efficient_attention", op, inp)

    out, *_ = op.apply(inp, needs_gradient=False)
    return out.reshape(output_shape)


def memory_efficient_attention_forward(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attn_bias: Optional[Union[torch.Tensor, AttentionBias]] = None,
    p: float = 0.0,
    scale: Optional[float] = None,
    *,
    op: Optional[Type[AttentionFwOpBase]] = None,
) -> torch.Tensor:
    """
    Calculates the forward pass of :attr:`xformers.ops.memory_efficient_attention`.
    """
    return _memory_efficient_attention_forward(
        Inputs(
            query=query, key=key, value=value, p=p, attn_bias=attn_bias, scale=scale
        ),
        op=op,
    )
```

**Comment by brcisna** [comment]
@wladradchenko 

When I do a remove pip uninstall xformers,,,then pip install xformers==0.0.19 it gets installed but then pull down regular version of pytorch 2.0.x I have pytorch 2.4.x-rocm
automagically xformers==0.0.28 gets installed (manually) after installing pytoch2.4.x-rocm
xformers                 0.0.28.post1

So,,,i tried placing the code you supplied 
at /venv/xformers/ops/_init_.py before lmha section.
When i started wunjo now,,it throws errors..
I probably placed the code in wrong file,,,
You are dealing with the braindead ,,,sorry

I probably placed the code you supplied in wrong xformers files?


TIA

**Comment by wladradchenko** [comment]
Not. I mean you need to (1) remove memory_efficient_attention_forward from import and (2) after all imports past the code

**Comment by brcisna** [comment]
@wladradchenko 

I see the second DEF stanza that you left
,,but not the first DEF stanza.

,,( you wanted me to delete both these i think i understood)?...

I appreciate your help.,.I am having trouble understanding,,,
I am attaching the _init_-.py file fresh,,,,from the/xformers/,,, fmha folder,,,,

As i said you can look ,,i only see the ;;;
--------------------------------------------------------------------------------------------
def memory_efficient_attention_forward(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attn_bias: Optional[Union[torch.Tensor, AttentionBias]] = None,
    p: float = 0.0,
    scale: Optional[float] = None,
    *,
    op: Optional[Type[AttentionFwOpBase]] = None,
) -> torch.Tensor:
    """
    Calculates the forward pass of :attr:`xformers.ops.memory_efficient_attention`.
    """
    return _memory_efficient_attention_forward(
        Inputs(
            query=query, key=key, value=value, p=p, attn_bias=attn_bias, scale=scale
        ),
        op=op,
    )

**Comment by brcisna** [comment]
@wladradchenko 

a little progress,,

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.1+cu121 with CUDA 1201 (you have 2.4.1+rocm6.0)
    Python  3.10.15 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
[SERVER][INFO][2024-09-20 12:21:48] http://127.0.0.1:8000

This is simlar,,,
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/16439

**Comment by wladradchenko** [comment]
@brcisna I think you can turn off xformers, for you is not necessary use this if you have problems with version. 

In folder generation, you can find [file](https://github.com/wladradchenko/wunjo.wladradchenko.ru/blob/main/portable%2Fsrc%2Fgeneration%2Fpipeline%2Fprocessing.py) with transformers. You need find all lines where is word xformers and remove. And after uninstall xformers.

**Comment by brcisna** [comment]
@wladradchenko 

I did delete all lines with xformers as you suggested. 

it generated for quite a while but then run out of memory,,I was just using the default animation photo with default text prompt to see if it would work.
Posting were it failed  this time.

If you prefer i stop posting,,,,here say so,,i am taking up a lot of your time.
In all the other modules everything generated fine..

SERVER][ERROR][127.0.0.1][2024-09-20 15:02:37] HIP out of memory. Tried to allocate 25.31 GiB. GPU 0 has a total capacity of 7.98 GiB of which 2.23 GiB is free. Of the allocated memory 5.05 GiB is allocated by PyTorch, and 320.58 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by wladradchenko** [comment]
@brcisna this is idea of xformers. For example I have Nvidia RTX 3060 8 GB VRAM, and with xformers I can use video generation, but without xformers, this require more 20 GB VRAM. 

Transformers lib use xformers 0.0.19 version. Maybe you need to this this repo to find answer how fix this issue on new versions of xformers.

**Comment by brcisna** [comment]
@wladradchenko 

this looked very promising..as they have a prebuilt xformers  with rocm embedded for the current Pytorch2.4.1 
It installed fine but the same error exists.

https://github.com/facebookresearch/xformers

Have spent a lot of time searching. Have not found one article that says xformers will work with rocm 
All the erroes boils down to the FP16 FB32 functioning stuff. 

I honestly thought as long as you were using Linux,, an AMD  Radeon recent card was pretty easy to use for AI stuff now.
Looking back,,should have certainly got an Nvidia card.
Rookie mistake.

**Comment by brcisna** [comment]
@wladradchenko 

Just wanted to share this.
Have been trying to compile xformers against PyTorch2.4.1 on Python3.10.12 
,,just to see if could get xformers to work with wunjo 
All my compilings keep getting error of 'no thrust/complex.h file found ( which is part of CUDA,,,I think)

But also someone was trying to compile for a card simlar to mine AMD Radeon Pro W6600 and one of the devs replied with the following: This is May 2024
-----------------------------------------------------------------------------------------------------
It's not supposed to work on gfx10xx or gfx11xx yet (as we haven't had developers' bandwidth to support it). The root cause is different matrix core instructions being used between different gfx families, as the compiler error is trying to hint.
The installation should work if you could get access to any MI2xx or MI3xx card (the datacenter GPU series)
I'll also leave a helpful link for gfx version deciphering
-----------------------------------------------------------------------------------------------------------
Barry
