### ISSUE TITLE
The RetinaFace-R50.pth file cannot be found.

### ISSUE THREAD

**Issue by wxc1207** [wladradchenko/wunjo.wladradchenko.ru#71]
[SERVER][ERROR][127.0.0.1][2024-10-12 19:32:22] Model not found at C:\Users\WXC\.wunjo\all_models\checkpoints\RetinaFace-R50.pth. The application cannot access the internet. Please allow Wunjo AI through your firewall or download the models manually. For more details, visit our documentation: https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki

The file RetinaFace-R50.pth download link was not found at the following URL:

https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/How-to-manually-set-models-for-deepfake-animation-of-the-face-and-lips

**Comment by wladradchenko** [comment]
Read the message carefully before creating an issue. It is written there in detail especially for you that you have denied access to the Internet to the application via the browndomer, then you need to download all the models yourself. The link and folder are indicated in the message, you can also go to the settings and see all the models and their folders for each module. Or allow access via the browndomer to the application to the Internet.
