### ISSUE TITLE
requirements_zluda.txt

### ISSUE THREAD

**Issue by brcisna** [wladradchenko/wunjo.wladradchenko.ru#72]
Debian 13
Python3.10.12
AMD Radeon Pro W6600

*EDIT*
wanted to say,this is not really an issue with wunjo in any way. It is just  trying to document what it took to get an AMD GPU to work. Didnt know where else to put this for posterity purposes.

Just wanted to share this for anyone trying to get AMD GPU working in general on AI PyTorch Apps.
Previously had a working setup of wunjo CE on Debian 

had to get a bigger nvme SSD as the models eat up a drive in no time.
after getting bigger nvme setup,,,I could not get the GPU to show in wunjo 
Spent a lot of time..
*RESOLVE* 
To cut to the quick. I had to install 'firmware-linux-nonfree' package!
By default on Debian install firmware-amd-graphics package was installed.
I had assumed that was all that was needed.

I used the requirements_zluda.txt file and thought everything was cosher,,, but could not get the GPU to be shown .
After installing the 'firmware-linux-nonfree' package the gpu was availble in wunjo.

All the documenation for rocm & hip is very much Ubuntu specific. 
Hope this may help someone.

TIA

**Comment by wladradchenko** [comment]
Hi, Thanks for your comment, I will definitely add it to README ❤️
