### ISSUE TITLE
xformers fails 

### ISSUE THREAD

**Issue by brcisna** [wladradchenko/wunjo.wladradchenko.ru#73]
Debian 13
Python3.10.0
Radeon Pro W6600 GPU

This is not wunjo issue at all. 
I reported this a few weeks back, With a  fresh installation,,,of Debian Trixie 13,,everything on wunjo works great with AMD GPU,,other than the generation funcion.
It ups up throwing the following error

[SERVER][INFO][127_0_0_1][2024-10-17 12:08:41] [Outpaint] Processing.
[SERVER][ERROR][127.0.0.1][2024-10-17 12:08:51] No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`ckF` is not supported because:
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    
    After much searching it is a problem with xformers for rocm, Everyone else reports the same problem,in different ways. 
    It appears the only AMD gpu's that will actually work, with xformers_rocm,, is the enterprise gpu A100 & M100 ( about 10,000 USD!)
    
    I tried compiling xformers_rocm,,, several times and always fails. Other reports the same.
    I did put an issure ticket at xformers_rocm,,,and hav e not seen any sort of response from devs there.  I think they have mentioend only GPU's that will work are the A100 & M100,,,as they have a particular sequencing behaihor,,,all their own. 
    
    Just wanted to share the current status.
    
    Thanks foir setting up the AMD gpu instruction in your redme/ instructions.

**Comment by wladradchenko** [comment]
Hi. Thanks for sharing the current status. Yes, unfortunately there are problems with AMD and XForms. You can comment out the line:

```
pipe.enable_xformers_memory_efficient_attention()
```

In file [portable/src/generation/pipeline
/processing.py](https://github.com/wladradchenko/wunjo.wladradchenko.ru/blob/main/portable/src/generation/pipeline/processing.py) else you can run on CPU without xformers by using RAM.

However, you will then need a lot of video memory.

**Comment by wladradchenko** [comment]
In recent improvements, I managed to upgrade versions to 

```
# CUDA
--extra-index-url https://download.pytorch.org/whl/cu118
torch==2.2.2; sys_platform == "win32"
torchaudio==2.2.2; sys_platform == "win32"
torchvision==0.17.2; sys_platform == "win32"
xformers==0.0.25post1; sys_platform == "win32"

--extra-index-url https://download.pytorch.org/whl/cu124
torch==2.4.0; sys_platform != "win32"
torchaudio==2.4.0; sys_platform != "win32"
torchvision==0.19.0; sys_platform != "win32"
xformers==0.0.27post2; sys_platform != "win32"
```

You also can use for Windows:

```
torch==2.4.0; sys_platform != "win32"
torchaudio==2.4.0; sys_platform != "win32"
torchvision==0.19.0; sys_platform != "win32"
xformers==0.0.27post2; sys_platform != "win32"
```

__I limited it because in the latest versions the behavior of Torch for Windows is inadequate. When installing CPU versions of libraries, it still requires CUDA 12.4. If you install CUDA, you can use torch 2.4.0__

But using build with xformers last version (0.0.28post2 and 0.0.28post3), I got similar problems with pipe.enable_xformers_memory_efficient_attention(). Maybe this information help you in research.
