### ISSUE TITLE
Не скачивает файлы

### ISSUE THREAD

**Issue by subbotaaa** [wladradchenko/wunjo.wladradchenko.ru#8]
Привет! Посмотрел примеры и приятно удивлен. Сразу захотел опробовать. 
Скачал готовую сборку под Windows, начал синтезировать речь. Прога выдала что нет файлов для синтеза и они скачаются. Но не чувствую это скачивание. Папка .wunjo весит 1 МБ и не увеличивается. Ошибок никаких не дает. Как-то можно вручную закинуть туда необходимые файлы? Не нашел в документации этого

Скрины:
https://disk.yandex.ru/i/pAnpZjZiA_5mOw
https://disk.yandex.ru/i/1dHNIBNrrOJTEw

**Comment by wladradchenko** [comment]
> Привет! Посмотрел примеры и приятно удивлен. Сразу захотел опробовать. Скачал готовую сборку под Windows, начал синтезировать речь. Прога выдала что нет файлов для синтеза и они скачаются. Но не чувствую это скачивание. Папка .wunjo весит 1 МБ и не увеличивается. Ошибок никаких не дает. Как-то можно вручную закинуть туда необходимые файлы? Не нашел в документации этого
> 
> Скрины: https://disk.yandex.ru/i/pAnpZjZiA_5mOw https://disk.yandex.ru/i/1dHNIBNrrOJTEw

Привет. Вы скачали версию 1.4, я бы все таки попросил вас сделать версию 1.5, она доступна со вчера. Вот оповещение же есть на скрин в нижнем левом экране. Там исправлены эти баги. Однако, если вы все таки хотите воспользоваться 1.4, для вас все таки все шаги описаны в документации, которая есть на русском и английском.

Документация для [синтеза речи](https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/%D0%9A%D0%B0%D0%BA-%D0%B2%D1%80%D1%83%D1%87%D0%BD%D1%83%D1%8E-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C-%D0%BF%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0-%D0%B2-%D1%80%D0%B5%D1%87%D1%8C)  и для [создания дипфейков](https://github.com/wladradchenko/wunjo.wladradchenko.ru/wiki/%D0%9A%D0%B0%D0%BA-%D0%B2%D1%80%D1%83%D1%87%D0%BD%D1%83%D1%8E-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8-%D0%B4%D0%BB%D1%8F-%D0%B4%D0%B8%D0%BF%D1%84%D0%B5%D0%B9%D0%BA%D0%B0-%D0%B0%D0%BD%D0%B8%D0%BC%D0%B0%D1%86%D0%B8%D0%B8-%D0%BB%D0%B8%D1%86%D0%B0-%D0%B8-%D0%B3%D1%83%D0%B1). К тому же ещё есть видео как установить на ютюб [канале](https://www.youtube.com/watch?v=oHQR1Zx6YOk&list=PLJG0sD6007zFJyV78mkU-KW2UxbirgTGr)
